// config.js
// Level metadata lives in shared/levelRegistry.js (loaded as a classic script
// before this module). Edit it there to add or rename levels.
export const CONFIG = {
    LEVEL_GROUPS: window.LevelRegistry.equations.LEVEL_GROUPS,
    REQUIRED_STREAK: 10,
    FEEDBACK_DELAY_CORRECT: 300,
    FEEDBACK_DELAY_INCORRECT: 1000,
    POSITIVE_FEEDBACK: ["Awesome!", "Great Job!", "You got it!", "Fantastic!", "Brilliant!", "Keep it up!", "Nice!", "Correct!"],
    SECOND_CHANCE_FEEDBACK: ["Try again", "Not quite right", "Have another go!", "Take another shot at it!"],
    RATING_THRESHOLDS: [
        { maxAvg: 2, name: "Maths Queen", key: "true-mastery" },
        { maxAvg: 3, name: "Mastery", key: "mastery" },
        { maxAvg: 4, name: "Expert", key: "expert" },
        { maxAvg: 5, name: "Developing", key: "developing" },
        { maxAvg: Infinity, name: "Beginner", key: "beginner" }
    ],
    // Calibrated so James Ding's personal-best time on each level lands just
    // inside the Maths Queen band (best_time * 1.1 / 20000, rounded up to the
    // nearest 0.5 below 4 / nearest whole at/above 4). See plan-calibrate-queen.
    LEVEL_DIFFICULTY_MULTIPLIERS: {
        // Foundational Skills
        'oneStepEasy': 1,
        'oneStepMedium': 1.5,
        'oneStepHard': 2,
        'twoStepEasy': 2,
        'twoStepMedium': 2.5,
        'twoStepHard': 3,
        'twoStepNegCoeffEasy': 2,
        'twoStepNegCoeffMedium': 2,
        'twoStepNegCoeffHard': 4,
        'twoStepGroupingEasy': 2,
        'twoStepGroupingMedium': 4,
        'twoStepGroupingHard': 5,
        'mixedTwoStepEasy': 2.5,
        'mixedTwoStepMedium': 2.5,
        'mixedTwoStepHard': 6,
        'simpleQuadraticEasy': 2,
        'simpleQuadraticMedium': 2,
        'simpleQuadraticHard': 4,
        'pronumeralsBothSidesEasy': 2.5,
        'pronumeralsBothSidesMedium': 3,
        'pronumeralsBothSidesHard': 3.5,
        // Intermediate Skills
        'mixedMultistepLinearEasy': 8,
        'mixedMultistepLinearMedium': 6,
        'mixedMultistepLinearHard': 9,
        'nullFactorLawEasy': 1.5,
        'nullFactorLawMedium': 3,
        'nullFactorLawHard': 6,
        'monicQuadraticEasy': 2.5,
        'monicQuadraticMedium': 3.5,
        'monicQuadraticHard': 9,
        'simpleCubicEasy': 3,
        'simpleCubicMedium': 3.5,
        'simpleCubicHard': 5,
        'linearInequalitiesEasy': 2,
        'linearInequalitiesMedium': 7,
        'linearInequalitiesHard': 9,
        // Advanced Skills
        'algFractMonomialEasy': 6,
        'algFractMonomialMedium': 8,
        'algFractMonomialHard': 15,
        'algFractBinomialEasy': 11,
        'algFractBinomialMedium': 13,
        'algFractBinomialHard': 16,
        'algFractCrossMultiplyEasy': 7,
        'algFractCrossMultiplyMedium': 12,
        'algFractCrossMultiplyHard': 17,
        'algFractAlgDenomEasy': 5,
        'algFractAlgDenomMedium': 6,
        'algFractAlgDenomHard': 12,
        'nonMonicQuadraticEasy': 11,
        'nonMonicQuadraticMedium': 20,
        'nonMonicQuadraticHard': 25,
        'quadraticFormulaEasy': 11,
        'quadraticFormulaMedium': 12,
        'quadraticFormulaHard': 33,
        'substitutionEasy': 9,
        'substitutionMedium': 11,
        'substitutionHard': 22,
        'eliminationEasy': 10,
        'eliminationMedium': 16,
        'eliminationHard': 26,
        'equatingCoefficientsEasy': 17,
        'equatingCoefficientsMedium': 21,
        'equatingCoefficientsHard': 23,
        'exponentialNoLogsEasy': 2,
        'exponentialNoLogsMedium': 5,
        'exponentialNoLogsHard': 9,
        'quadraticInequalitiesEasy': 5,
        'quadraticInequalitiesMedium': 15,
        'quadraticInequalitiesHard': 21,
        'trigEquationsEasy': 5,
        'trigEquationsMedium': 17,
        'trigEquationsHard': 22,
    },
    CONFETTI: { CORRECT: 40, SUCCESS: 150 }
};
