// config.js
// Level metadata lives in shared/levelRegistry.js (loaded as a classic script
// before this module). Edit it there to add or rename levels.
export const CONFIG = {
    LEVEL_GROUPS: window.LevelRegistry.equations.LEVEL_GROUPS,
    REQUIRED_STREAK: 10,
    FEEDBACK_DELAY_CORRECT: 300,
    FEEDBACK_DELAY_INCORRECT: 1000,
    POSITIVE_FEEDBACK: ["Awesome!", "Great Job!", "You got it!", "Fantastic!", "Brilliant!", "Keep it up!", "Nice!", "Correct!"],
    SECOND_CHANCE_FEEDBACK: ["Try again", "Not quite right", "Have another go!", "Take another shot at it!"],
    RATING_THRESHOLDS: [
        { maxAvg: 2, name: "Maths Queen", key: "true-mastery" },
        { maxAvg: 3, name: "Mastery", key: "mastery" },
        { maxAvg: 5, name: "Expert", key: "expert" },
        { maxAvg: 10, name: "Developing", key: "developing" },
        { maxAvg: Infinity, name: "Beginner", key: "beginner" }
    ],
    LEVEL_DIFFICULTY_MULTIPLIERS: {
        // Foundational Skills
        'oneStepEasy': 1.5,
        'oneStepMedium': 1.8,
        'oneStepHard': 2.0,
        'twoStepEasy': 1.8,
        'twoStepMedium': 2.0,
        'twoStepHard': 3.2,
        'twoStepNegCoeffEasy': 1.8,
        'twoStepNegCoeffMedium': 2.3,
        'twoStepNegCoeffHard': 3.8,
        'twoStepGroupingEasy': 2.5,
        'twoStepGroupingMedium': 4.5,
        'twoStepGroupingHard': 5.0,
        'mixedTwoStepEasy': 2.5,
        'mixedTwoStepMedium': 5.0,
        'mixedTwoStepHard': 7.0,
        'simpleQuadraticEasy': 2.0,
        'simpleQuadraticMedium': 2.0,
        'simpleQuadraticHard': 5.0,
        'pronumeralsBothSidesEasy': 2.0,
        'pronumeralsBothSidesMedium': 3.8,
        'pronumeralsBothSidesHard': 4.2,
        // Intermediate Skills
        'mixedMultistepLinearEasy': 7.0,
        'mixedMultistepLinearMedium': 8.0,
        'mixedMultistepLinearHard': 9.0,
        'nullFactorLawEasy': 1.5,
        'nullFactorLawMedium': 2.5,
        'nullFactorLawHard': 7.0,
        'monicQuadraticEasy': 3.5,
        'monicQuadraticMedium': 4.0,
        'monicQuadraticHard': 9.0,
        'simpleCubicEasy': 3.0,
        'simpleCubicMedium': 3.5,
        'simpleCubicHard': 4,
        'linearInequalitiesEasy': 3.0,
        'linearInequalitiesMedium': 7,
        'linearInequalitiesHard': 10.0,
        // Advanced Skills
        'algFractMonomialEasy': 7.0,
        'algFractMonomialMedium': 10.0,
        'algFractMonomialHard': 14.0,
        'algFractBinomialEasy': 9.0,
        'algFractBinomialMedium': 12.0,
        'algFractBinomialHard': 17.0,
        'algFractCrossMultiplyEasy': 8.0,
        'algFractCrossMultiplyMedium': 11.0,
        'algFractCrossMultiplyHard': 15.0,
        'algFractAlgDenomEasy': 10.0,
        'algFractAlgDenomMedium': 14.0,
        'algFractAlgDenomHard': 20.0,
        'nonMonicQuadraticEasy': 8.0,
        'nonMonicQuadraticMedium': 11.0,
        'nonMonicQuadraticHard': 15.0,
        'quadraticFormulaEasy': 10.0,
        'quadraticFormulaMedium': 14.0,
        'quadraticFormulaHard': 20.0,
        'substitutionEasy': 10.0,
        'substitutionMedium': 14.0,
        'substitutionHard': 20.0,
        'eliminationEasy': 8.0,
        'eliminationMedium': 11.0,
        'eliminationHard': 15.0,
        'equatingCoefficientsEasy': 10.0,
        'equatingCoefficientsMedium': 14.0,
        'equatingCoefficientsHard': 20.0,
        'exponentialNoLogsEasy': 6.0,
        'exponentialNoLogsMedium': 8.0,
        'exponentialNoLogsHard': 11.0,
        'quadraticInequalitiesEasy': 9.0,
        'quadraticInequalitiesMedium': 12.0,
        'quadraticInequalitiesHard': 17.0,
    },
    STORAGE_PREFIX: 'equations_bestTime_v1_',
    CONFETTI: { CORRECT: 40, SUCCESS: 150 }
};
