import { BaseLevel } from './BaseLevel.js';

export default new BaseLevel('exponentialDiffRulesHard', 'Exponential with Rules — Hard', [
  { problem: '\\frac{d}{dx}\\left(\\frac{e^{3x}}{x^2}\\right)', answer: '\\frac{e^{3x}(3x-2)}{x^3}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{e^{2x+1}}{2x+5}\\right)', answer: '\\frac{4e^{2x+1}(x+2)}{(2x+5)^2}' },
  { problem: '\\frac{d}{dx}(x^2\\cdot 4^x)', answer: '4^x(2x+x^2\\ln 4)' },
  { problem: '\\frac{d}{dx}((x^2+1)e^{3x})', answer: 'e^{3x}(3x^2+2x+3)' },
  { problem: '\\frac{d}{dx}((x^3-x)e^{2x})', answer: 'e^{2x}(2x^3+3x^2-2x-1)' },
  { problem: '\\frac{d}{dx}((x^2+2x+2)e^{-x})', answer: '-x^2e^{-x}' },
  { problem: '\\frac{d}{dx}(x^4e^{-x})', answer: 'x^3e^{-x}(4-x)' },
  { problem: '\\frac{d}{dx}((2x^2-3x)e^x)', answer: 'e^x(2x^2+x-3)' },
  { problem: '\\frac{d}{dx}(x^4e^{2x})', answer: '2x^3e^{2x}(2+x)' },
  { problem: '\\frac{d}{dx}((x^2-4)e^{3x})', answer: 'e^{3x}(3x^2+2x-12)' },
  { problem: '\\frac{d}{dx}((x^2+x)e^{2x})', answer: 'e^{2x}(2x^2+4x+1)' },
  { problem: '\\frac{d}{dx}(x^3e^{4x})', answer: 'x^2e^{4x}(3+4x)' },
  { problem: '\\frac{d}{dx}((3x-2)e^{2x})', answer: 'e^{2x}(6x-1)' },
  { problem: '\\frac{d}{dx}((x^3+2x)e^{-2x})', answer: 'e^{-2x}(-2x^3+3x^2-4x+2)' },
  { problem: '\\frac{d}{dx}((x^2-x+1)e^x)', answer: 'xe^x(x+1)' },
  { problem: '\\frac{d}{dx}((x^3+x^2)e^{2x})', answer: 'e^{2x}(2x^3+5x^2+2x)' },
  { problem: '\\frac{d}{dx}((4x-1)e^{3x})', answer: 'e^{3x}(12x+1)' },
  { problem: '\\frac{d}{dx}\\left(\\frac{e^{3x}}{x^3}\\right)', answer: '\\frac{3e^{3x}(x-1)}{x^4}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{e^{2x}}{x^3}\\right)', answer: '\\frac{e^{2x}(2x-3)}{x^4}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{e^x}{x^4}\\right)', answer: '\\frac{e^x(x-4)}{x^5}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{e^{4x}}{x^2}\\right)', answer: '\\frac{2e^{4x}(2x-1)}{x^3}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{e^{3x}}{x^4}\\right)', answer: '\\frac{e^{3x}(3x-4)}{x^5}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x^3}{e^x}\\right)', answer: '\\frac{x^2(3-x)}{e^x}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x^2+1}{e^{2x}}\\right)', answer: '-\\frac{2(x^2-x+1)}{e^{2x}}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x^2-1}{e^{3x}}\\right)', answer: '\\frac{3+2x-3x^2}{e^{3x}}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x^4}{e^{2x}}\\right)', answer: '\\frac{2x^3(2-x)}{e^{2x}}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x^3+x}{e^x}\\right)', answer: '\\frac{-x^3+3x^2-x+1}{e^x}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{e^{2x}}{x^2+1}\\right)', answer: '\\frac{2e^{2x}(x^2-x+1)}{(x^2+1)^2}' },
], { mode: 'derivative', toleranceDp: 2 });
