import { BaseLevel } from './BaseLevel.js';

export default new BaseLevel('exponentialDiffRulesEasy', 'Exponential with Rules — Easy', [
  { problem: '\\frac{d}{dx}(xe^x)', answer: 'e^x(1+x)' },
  { problem: '\\frac{d}{dx}(xe^{2x})', answer: 'e^{2x}(1+2x)' },
  { problem: '\\frac{d}{dx}(x^2e^x)', answer: 'xe^x(2+x)' },
  { problem: '\\frac{d}{dx}(x^2e^{3x})', answer: 'xe^{3x}(2+3x)' },
  { problem: '\\frac{d}{dx}(x^3e^x)', answer: 'x^2e^x(3+x)' },
  { problem: '\\frac{d}{dx}(xe^{-x})', answer: 'e^{-x}(1-x)' },
  { problem: '\\frac{d}{dx}(x^2e^{-x})', answer: 'xe^{-x}(2-x)' },
  { problem: '\\frac{d}{dx}(xe^{3x})', answer: 'e^{3x}(1+3x)' },
  { problem: '\\frac{d}{dx}(x^2e^{2x})', answer: '2xe^{2x}(1+x)' },
  { problem: '\\frac{d}{dx}(xe^{4x})', answer: 'e^{4x}(1+4x)' },
  { problem: '\\frac{d}{dx}(xe^{-2x})', answer: 'e^{-2x}(1-2x)' },
  { problem: '\\frac{d}{dx}(x^3e^{2x})', answer: 'x^2e^{2x}(3+2x)' },
  { problem: '\\frac{d}{dx}\\left(\\frac{e^x}{x}\\right)', answer: '\\frac{e^x(x-1)}{x^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{e^x}{x^2}\\right)', answer: '\\frac{e^x(x-2)}{x^3}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{e^{2x}}{x}\\right)', answer: '\\frac{e^{2x}(2x-1)}{x^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{e^{3x}}{x}\\right)', answer: '\\frac{e^{3x}(3x-1)}{x^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{e^x}{x^3}\\right)', answer: '\\frac{e^x(x-3)}{x^4}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x}{e^x}\\right)', answer: '\\frac{1-x}{e^x}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x^2}{e^x}\\right)', answer: '\\frac{x(2-x)}{e^x}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{e^{2x}}{x^2}\\right)', answer: '\\frac{2e^{2x}(x-1)}{x^3}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{e^{-x}}{x}\\right)', answer: '-\\frac{e^{-x}(x+1)}{x^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x^3}{e^{2x}}\\right)', answer: '\\frac{x^2(3-2x)}{e^{2x}}' },
  { problem: '\\frac{d}{dx}(2xe^x)', answer: '2e^x(1+x)' },
  { problem: '\\frac{d}{dx}(3xe^{2x})', answer: '3e^{2x}(1+2x)' },
  { problem: '\\frac{d}{dx}(5x^2e^x)', answer: '5xe^x(2+x)' },
  { problem: '\\frac{d}{dx}((x+1)e^x)', answer: 'e^x(x+2)' },
  { problem: '\\frac{d}{dx}((x-1)e^{2x})', answer: 'e^{2x}(2x-1)' },
  { problem: '\\frac{d}{dx}((2x+3)e^x)', answer: 'e^x(2x+5)' },
  { problem: '\\frac{d}{dx}((x+1)e^{3x})', answer: 'e^{3x}(3x+4)' },
  { problem: '\\frac{d}{dx}((x-2)e^{2x})', answer: 'e^{2x}(2x-3)' },
], { mode: 'derivative', toleranceDp: 2 });
