import { BaseLevel } from './BaseLevel.js';

export default new BaseLevel('exponentialDiffRulesMedium', 'Exponential with Rules — Medium', [
  { problem: '\\frac{d}{dx}(xe^{x^2})', answer: 'e^{x^2}(1+2x^2)' },
  { problem: '\\frac{d}{dx}(x^2e^{x^2})', answer: '2xe^{x^2}(1+x^2)' },
  { problem: '\\frac{d}{dx}(x^3e^{x^2})', answer: 'x^2e^{x^2}(3+2x^2)' },
  { problem: '\\frac{d}{dx}(xe^{x^3})', answer: 'e^{x^3}(1+3x^3)' },
  { problem: '\\frac{d}{dx}(x^2e^{x^3})', answer: 'xe^{x^3}(2+3x^3)' },
  { problem: '\\frac{d}{dx}(x^4e^x)', answer: 'x^3e^x(4+x)' },
  { problem: '\\frac{d}{dx}(x^4e^{2x})', answer: '2x^3e^{2x}(2+x)' },
  { problem: '\\frac{d}{dx}(x^5e^x)', answer: 'x^4e^x(5+x)' },
  { problem: '\\frac{d}{dx}\\left(\\frac{e^{2x}}{2x+1}\\right)', answer: '\\frac{4xe^{2x}}{(2x+1)^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{e^{3x}}{3x-1}\\right)', answer: '\\frac{3(3x-2)e^{3x}}{(3x-1)^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{e^x}{x+1}\\right)', answer: '\\frac{xe^x}{(x+1)^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{e^{2x}}{x+2}\\right)', answer: '\\frac{e^{2x}(2x+3)}{(x+2)^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x+1}{e^x}\\right)', answer: '-\\frac{x}{e^x}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x+1}{e^{3x}}\\right)', answer: '-\\frac{3x+2}{e^{3x}}' },
  { problem: '\\frac{d}{dx}(xe^{2x^2})', answer: 'e^{2x^2}(1+4x^2)' },
  { problem: '\\frac{d}{dx}(xe^{x^2+x})', answer: 'e^{x^2+x}(2x^2+x+1)' },
  { problem: '\\frac{d}{dx}\\left(\\frac{e^{x^2}}{x}\\right)', answer: '\\frac{e^{x^2}(2x^2-1)}{x^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{e^{x^2}}{x^2}\\right)', answer: '\\frac{2e^{x^2}(x^2-1)}{x^3}' },
  { problem: '\\frac{d}{dx}(x\\cdot 2^x)', answer: '2^x(1+x\\ln 2)' },
  { problem: '\\frac{d}{dx}(x\\cdot 3^x)', answer: '3^x(1+x\\ln 3)' },
  { problem: '\\frac{d}{dx}(x^2\\cdot 2^x)', answer: 'x\\cdot 2^x(2+x\\ln 2)' },
  { problem: '\\frac{d}{dx}\\left(\\frac{e^{x^2}}{x+1}\\right)', answer: '\\frac{e^{x^2}(2x^2+2x-1)}{(x+1)^2}' },
  { problem: '\\frac{d}{dx}(x^2e^{-x^2})', answer: '2xe^{-x^2}(1-x^2)' },
  { problem: '\\frac{d}{dx}(xe^{x^2+2x})', answer: 'e^{x^2+2x}(2x^2+2x+1)' },
  { problem: '\\frac{d}{dx}(x^3e^{3x})', answer: '3x^2e^{3x}(1+x)' },
  { problem: '\\frac{d}{dx}(x^2e^{-2x})', answer: '2xe^{-2x}(1-x)' },
  { problem: '\\frac{d}{dx}(x^3e^{-x})', answer: 'x^2e^{-x}(3-x)' },
  { problem: '\\frac{d}{dx}(e^{2x}(x^2-1))', answer: '2e^{2x}(x^2+x-1)' },
  { problem: '\\frac{d}{dx}\\left(\\frac{e^{3x}}{x^2+1}\\right)', answer: '\\frac{e^{3x}(3x^2-2x+3)}{(x^2+1)^2}' },
  { problem: '\\frac{d}{dx}(x\\cdot 5^x)', answer: '5^x(1+x\\ln 5)' },
], { mode: 'derivative', toleranceDp: 2 });
