import { BaseLevel } from './BaseLevel.js';

export default new BaseLevel('exponentialDiffEasy', 'Exponential Functions — Easy', [
  { problem: '\\frac{d}{dx}(e^{7x})', answer: '7e^{7x}' },
  { problem: '\\frac{d}{dx}(e^{-x})', answer: '-e^{-x}' },
  { problem: '\\frac{d}{dx}(e^{6x-2})', answer: '6e^{6x-2}' },
  { problem: '\\frac{d}{dx}(e^{-2x})', answer: '-2e^{-2x}' },
  { problem: '\\frac{d}{dx}(e^{10x})', answer: '10e^{10x}' },
  { problem: '\\frac{d}{dx}(e^{5x})', answer: '5e^{5x}' },
  { problem: '\\frac{d}{dx}(e^{2x}+x)', answer: '2e^{2x}+1' },
  { problem: '\\frac{d}{dx}(e^{3x})', answer: '3e^{3x}' },
  { problem: '\\frac{d}{dx}(e^{4x})', answer: '4e^{4x}' },
  { problem: '\\frac{d}{dx}(e^{8x})', answer: '8e^{8x}' },
  { problem: '\\frac{d}{dx}(e^{9x})', answer: '9e^{9x}' },
  { problem: '\\frac{d}{dx}\\left(e^{\\frac{x}{2}}\\right)', answer: '\\frac{1}{2}e^{\\frac{x}{2}}' },
  { problem: '\\frac{d}{dx}\\left(e^{\\frac{x}{3}}\\right)', answer: '\\frac{1}{3}e^{\\frac{x}{3}}' },
  { problem: '\\frac{d}{dx}(e^{-3x})', answer: '-3e^{-3x}' },
  { problem: '\\frac{d}{dx}(e^{-4x})', answer: '-4e^{-4x}' },
  { problem: '\\frac{d}{dx}(e^{2x+1})', answer: '2e^{2x+1}' },
  { problem: '\\frac{d}{dx}(e^{3x-1})', answer: '3e^{3x-1}' },
  { problem: '\\frac{d}{dx}(e^{-x+2})', answer: '-e^{-x+2}' },
  { problem: '\\frac{d}{dx}(e^{4x+3})', answer: '4e^{4x+3}' },
  { problem: '\\frac{d}{dx}(e^{-5x+1})', answer: '-5e^{-5x+1}' },
  { problem: '\\frac{d}{dx}(3e^{2x})', answer: '6e^{2x}' },
  { problem: '\\frac{d}{dx}(4e^{3x})', answer: '12e^{3x}' },
  { problem: '\\frac{d}{dx}(5e^{-x})', answer: '-5e^{-x}' },
  { problem: '\\frac{d}{dx}(2e^{4x}+3)', answer: '8e^{4x}' },
  { problem: '\\frac{d}{dx}(e^{x}+e^{-x})', answer: 'e^{x}-e^{-x}' },
  { problem: '\\frac{d}{dx}(e^{3x}+2x^2)', answer: '3e^{3x}+4x' },
  { problem: '\\frac{d}{dx}(e^{-2x}+5x)', answer: '-2e^{-2x}+5' },
  { problem: '\\frac{d}{dx}\\left(3e^{\\frac{x}{2}}\\right)', answer: '\\frac{3}{2}e^{\\frac{x}{2}}' },
  { problem: '\\frac{d}{dx}(2e^{-3x}+x^2)', answer: '-6e^{-3x}+2x' },
  { problem: '\\frac{d}{dx}(e^{x}+x^3)', answer: 'e^{x}+3x^2' },
], { mode: 'derivative' });
