import { BaseLevel } from './BaseLevel.js';

export default new BaseLevel('exponentialDiffMedium', 'Exponential Functions — Medium', [
  { problem: '\\frac{d}{dx}(e^{x^2+1})', answer: '2xe^{x^2+1}' },
  { problem: '\\frac{d}{dx}(e^{x^3+5x+7})', answer: '(3x^2+5)e^{x^3+5x+7}' },
  { problem: '\\frac{d}{dx}(x^2+2x+e^{1-x})', answer: '2x+2-e^{1-x}' },
  { problem: '\\frac{d}{dx}(2^x)', answer: '2^x\\ln 2' },
  { problem: '\\frac{d}{dx}(e^x+3^x)', answer: 'e^x+3^x\\ln 3' },
  { problem: '\\frac{d}{dx}(e^{x^2})', answer: '2xe^{x^2}' },
  { problem: '\\frac{d}{dx}(e^{x^2-3x})', answer: '(2x-3)e^{x^2-3x}' },
  { problem: '\\frac{d}{dx}(e^{2x^2+1})', answer: '4xe^{2x^2+1}' },
  { problem: '\\frac{d}{dx}(e^{x^3})', answer: '3x^2e^{x^3}' },
  { problem: '\\frac{d}{dx}(e^{x^2+x})', answer: '(2x+1)e^{x^2+x}' },
  { problem: '\\frac{d}{dx}(e^{3x^2-x})', answer: '(6x-1)e^{3x^2-x}' },
  { problem: '\\frac{d}{dx}(e^{x^2+2x+1})', answer: '2(x+1)e^{x^2+2x+1}' },
  { problem: '\\frac{d}{dx}(e^{x^4+3})', answer: '4x^3e^{x^4+3}' },
  { problem: '\\frac{d}{dx}(3^x)', answer: '3^x\\ln 3' },
  { problem: '\\frac{d}{dx}(5^x)', answer: '5^x\\ln 5' },
  { problem: '\\frac{d}{dx}(10^x)', answer: '10^x\\ln 10' },
  { problem: '\\frac{d}{dx}(4^x)', answer: '4^x\\ln 4' },
  { problem: '\\frac{d}{dx}(2^x+3^x)', answer: '2^x\\ln 2+3^x\\ln 3' },
  { problem: '\\frac{d}{dx}(4^x-5^x)', answer: '4^x\\ln 4-5^x\\ln 5' },
  { problem: '\\frac{d}{dx}(e^{x^2}+x)', answer: '2xe^{x^2}+1' },
  { problem: '\\frac{d}{dx}(e^{x^3-1})', answer: '3x^2e^{x^3-1}' },
  { problem: '\\frac{d}{dx}(e^{2x^2-3x+1})', answer: '(4x-3)e^{2x^2-3x+1}' },
  { problem: '\\frac{d}{dx}(x^3+e^{x^2})', answer: '3x^2+2xe^{x^2}' },
  { problem: '\\frac{d}{dx}(e^{x^2}+e^{-x})', answer: '2xe^{x^2}-e^{-x}' },
  { problem: '\\frac{d}{dx}(2^x+e^{2x})', answer: '2^x\\ln 2+2e^{2x}' },
], { mode: 'derivative' });
