import { BaseLevel } from './BaseLevel.js';

export default new BaseLevel('exponentialDiffHard', 'Exponential Functions — Hard', [
  { problem: '\\frac{d}{dx}((x+e^{4x})^5)', answer: '5(1+4e^{4x})(x+e^{4x})^4' },
  { problem: '\\frac{d}{dx}((e^{2x}+x)^3)', answer: '3(2e^{2x}+1)(e^{2x}+x)^2' },
  { problem: '\\frac{d}{dx}((e^{3x}+1)^4)', answer: '12e^{3x}(e^{3x}+1)^3' },
  { problem: '\\frac{d}{dx}((e^{x}+x^2)^3)', answer: '3(e^x+2x)(e^x+x^2)^2' },
  { problem: '\\frac{d}{dx}((x^2+e^{x})^5)', answer: '5(2x+e^x)(x^2+e^x)^4' },
  { problem: '\\frac{d}{dx}((e^{2x}+x^3)^4)', answer: '4(2e^{2x}+3x^2)(e^{2x}+x^3)^3' },
  { problem: '\\frac{d}{dx}((e^{-x}+x)^4)', answer: '4(1-e^{-x})(e^{-x}+x)^3' },
  { problem: '\\frac{d}{dx}((e^{5x}+2)^3)', answer: '15e^{5x}(e^{5x}+2)^2' },
  { problem: '\\frac{d}{dx}((1+e^{x})^6)', answer: '6e^x(1+e^x)^5' },
  { problem: '\\frac{d}{dx}((x+e^{-2x})^5)', answer: '5(1-2e^{-2x})(x+e^{-2x})^4' },
  { problem: '\\frac{d}{dx}((e^{3x}-x)^4)', answer: '4(3e^{3x}-1)(e^{3x}-x)^3' },
  { problem: '\\frac{d}{dx}((e^{x}+e^{-x})^3)', answer: '3(e^x-e^{-x})(e^x+e^{-x})^2' },
  { problem: '\\frac{d}{dx}((x^3+e^{2x})^5)', answer: '5(3x^2+2e^{2x})(x^3+e^{2x})^4' },
  { problem: '\\frac{d}{dx}((e^{x^2}+1)^3)', answer: '6xe^{x^2}(e^{x^2}+1)^2' },
  { problem: '\\frac{d}{dx}((e^{x^2}+x)^3)', answer: '3(2xe^{x^2}+1)(e^{x^2}+x)^2' },
  { problem: '\\frac{d}{dx}\\left(\\sqrt{e^{2x}+1}\\right)', answer: '\\frac{e^{2x}}{\\sqrt{e^{2x}+1}}' },
  { problem: '\\frac{d}{dx}\\left(\\sqrt{e^{4x}+x}\\right)', answer: '\\frac{4e^{4x}+1}{2\\sqrt{e^{4x}+x}}' },
  { problem: '\\frac{d}{dx}\\left(\\sqrt{e^x+x^2}\\right)', answer: '\\frac{e^x+2x}{2\\sqrt{e^x+x^2}}' },
  { problem: '\\frac{d}{dx}\\left(\\sqrt{e^{3x}-1}\\right)', answer: '\\frac{3e^{3x}}{2\\sqrt{e^{3x}-1}}' },
  { problem: '\\frac{d}{dx}\\left(\\sqrt{1+e^{-x}}\\right)', answer: '-\\frac{e^{-x}}{2\\sqrt{1+e^{-x}}}' },
  { problem: '\\frac{d}{dx}(e^{e^x})', answer: 'e^xe^{e^x}' },
  { problem: '\\frac{d}{dx}(e^{e^{2x}})', answer: '2e^{2x}e^{e^{2x}}' },
  { problem: '\\frac{d}{dx}(e^{e^x+x})', answer: '(e^x+1)e^{e^x+x}' },
  { problem: '\\frac{d}{dx}(e^{\\sin x})', answer: '\\cos x\\cdot e^{\\sin x}' },
  { problem: '\\frac{d}{dx}(e^{\\cos x})', answer: '-\\sin x\\cdot e^{\\cos x}' },
  { problem: '\\frac{d}{dx}(e^{\\tan x})', answer: '\\sec^2 x\\cdot e^{\\tan x}' },
  { problem: '\\frac{d}{dx}\\left(e^{\\sqrt{x}}\\right)', answer: '\\frac{e^{\\sqrt{x}}}{2\\sqrt{x}}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{1}{(e^x+1)^2}\\right)', answer: '-\\frac{2e^x}{(e^x+1)^3}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{1}{e^{2x}+1}\\right)', answer: '-\\frac{2e^{2x}}{(e^{2x}+1)^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{1}{(e^{3x}+x)^4}\\right)', answer: '-\\frac{4(3e^{3x}+1)}{(e^{3x}+x)^5}' },
], { mode: 'derivative' });
