import { BaseLevel } from './BaseLevel.js';

export default new BaseLevel('integrationBySubstitutionHard', 'Integration by Substitution — Hard', [
  { problem: '\\int\\frac{1}{\\sqrt{x}(1+\\sqrt{x})^3}\\,dx,\\quad\\text{let }u=1+\\sqrt{x}', answer: '-\\frac{1}{(1+\\sqrt{x})^2}+C' },
  { problem: '\\int x^2\\sqrt{1-x}\\,dx,\\quad\\text{let }u=1-x', answer: '-\\frac{2}{7}(1-x)^{\\frac{7}{2}}+\\frac{4}{5}(1-x)^{\\frac{5}{2}}-\\frac{2}{3}(1-x)^{\\frac{3}{2}}+C' },
  { problem: '\\int_0^{\\frac{\\pi}{2}}\\frac{\\cos x}{1+\\sin^2 x}\\,dx,\\quad\\text{let }u=\\sin x', answer: '\\frac{\\pi}{4}' },
  { problem: '\\int_{\\frac{\\pi}{6}}^{\\frac{\\pi}{2}}\\frac{\\cos^3 x}{\\sin^4 x}\\,dx,\\quad\\text{let }u=\\sin x', answer: '\\frac{4}{3}' },
  { problem: '\\int\\frac{\\tan x}{\\ln(\\cos x)}\\,dx,\\quad\\text{let }u=\\ln(\\cos x)', answer: '-\\ln(-\\ln(\\cos x))+C' },
  { problem: '\\int\\tan^3 x\\sec^4 x\\,dx,\\quad\\text{let }u=\\tan x', answer: '\\frac{1}{4}\\tan^4 x+\\frac{1}{6}\\tan^6 x+C' },
  { problem: '\\int_0^{\\frac{\\pi}{3}}2^{\\sec x}\\sec x\\tan x\\,dx,\\quad\\text{let }u=\\sec x', answer: '\\frac{2}{\\ln 2}' },
  { problem: '\\int_0^{\\frac{\\pi}{4}}\\sec^5 x\\tan x\\,dx,\\quad\\text{let }u=\\sec x', answer: '\\frac{4\\sqrt{2}-1}{5}' },
  { problem: '\\int_1^e\\frac{\\ln x+1}{(x\\ln x+1)^2}\\,dx,\\quad\\text{let }u=x\\ln x+1', answer: '\\frac{e}{e+1}' },
  { problem: '\\int\\frac{1}{2x\\sqrt{x-1}}\\,dx,\\quad\\text{let }u=\\sqrt{x-1}', answer: '\\tan^{-1}\\sqrt{x-1}+C' },
  { problem: '\\int 3x\\sqrt{4x-5}\\,dx,\\quad\\text{let }u=4x-5', answer: '\\frac{3}{40}(4x-5)^{\\frac{5}{2}}+\\frac{5}{8}(4x-5)^{\\frac{3}{2}}+C' },
  { problem: '\\int\\frac{1}{1+\\sqrt{x}}\\,dx,\\quad\\text{let }u=\\sqrt{x}', answer: '2(1+\\sqrt{x})-2\\ln(1+\\sqrt{x})+C' },
  { problem: '\\int_0^4 x\\sqrt{4-x}\\,dx,\\quad\\text{let }u=4-x', answer: '\\frac{128}{15}' },
  { problem: '\\int_1^5\\frac{x}{(2x-1)^{\\frac{3}{2}}}\\,dx,\\quad\\text{let }u=2x-1', answer: '\\frac{4}{3}' },
  { problem: '\\int x^3\\sqrt{x^2+1}\\,dx,\\quad\\text{let }u=x^2+1', answer: '\\frac{1}{5}(x^2+1)^{\\frac{5}{2}}-\\frac{1}{3}(x^2+1)^{\\frac{3}{2}}+C' },
  { problem: '\\int x^5\\sqrt{x^3+1}\\,dx,\\quad\\text{let }u=x^3+1', answer: '\\frac{2}{15}(x^3+1)^{\\frac{5}{2}}-\\frac{2}{9}(x^3+1)^{\\frac{3}{2}}+C' },
  { problem: '\\int\\sec^4 x\\,dx,\\quad\\text{let }u=\\tan x', answer: '\\tan x+\\frac{1}{3}\\tan^3 x+C' },
  { problem: '\\int\\sin^5 x\\,dx,\\quad\\text{let }u=\\cos x', answer: '-\\cos x+\\frac{2}{3}\\cos^3 x-\\frac{1}{5}\\cos^5 x+C' },
  { problem: '\\int\\cos^5 x\\,dx,\\quad\\text{let }u=\\sin x', answer: '\\sin x-\\frac{2}{3}\\sin^3 x+\\frac{1}{5}\\sin^5 x+C' },
  { problem: '\\int\\tan^3 x\\,dx,\\quad\\text{let }u=\\cos x', answer: '\\frac{1}{2}\\tan^2 x+\\ln(\\cos x)+C' },
  { problem: '\\int_0^1 x^3\\sqrt{1-x^2}\\,dx,\\quad\\text{let }u=1-x^2', answer: '\\frac{2}{15}' },
  { problem: '\\int\\frac{\\sqrt{x}}{1+x}\\,dx,\\quad\\text{let }u=\\sqrt{x}', answer: '2\\sqrt{x}-2\\tan^{-1}\\sqrt{x}+C' },
  { problem: '\\int\\frac{1}{\\sqrt{x}(1+x)}\\,dx,\\quad\\text{let }u=\\sqrt{x}', answer: '2\\tan^{-1}\\sqrt{x}+C' },
  { problem: '\\int\\frac{e^{2x}}{1+e^x}\\,dx,\\quad\\text{let }u=e^x', answer: 'e^x-\\ln(1+e^x)+C' },
  { problem: '\\int\\frac{1}{e^x+1}\\,dx,\\quad\\text{let }u=e^x', answer: 'x-\\ln(e^x+1)+C' },
  { problem: '\\int x^3 e^{x^2}\\,dx,\\quad\\text{let }u=x^2', answer: '\\frac{1}{2}e^{x^2}(x^2-1)+C' },
  { problem: '\\int\\frac{\\cos^3 x}{\\sqrt{\\sin x}}\\,dx,\\quad\\text{let }u=\\sin x', answer: '2\\sqrt{\\sin x}-\\frac{2}{5}(\\sin x)^{\\frac{5}{2}}+C' },
  { problem: '\\int_0^{\\frac{\\pi}{4}}\\tan^3 x\\sec^2 x\\,dx,\\quad\\text{let }u=\\tan x', answer: '\\frac{1}{4}' },
  { problem: '\\int_0^{\\frac{\\pi}{2}}\\sin^3 x\\cos^2 x\\,dx,\\quad\\text{let }u=\\cos x', answer: '\\frac{2}{15}' },
  { problem: '\\int\\frac{x^2}{x-1}\\,dx,\\quad\\text{let }u=x-1', answer: '\\frac{x^2}{2}+x+\\ln(x-1)+C' },
  { problem: '\\int_1^2 x^2\\sqrt{x-1}\\,dx,\\quad\\text{let }u=x-1', answer: '\\frac{184}{105}' },
], { mode: 'integral', toleranceDp: 4 });
