import { BaseLevel } from './BaseLevel.js';

export default new BaseLevel('integrationBySubstitutionMedium', 'Integration by Substitution — Medium', [
  { problem: '\\int\\tan^2(2x)\\sec^2(2x)\\,dx,\\quad\\text{let }u=\\tan(2x)', answer: '\\frac{1}{6}\\tan^3(2x)+C' },
  { problem: '\\int\\frac{e^{\\frac{1}{x}}}{x^2}\\,dx,\\quad\\text{let }u=\\frac{1}{x}', answer: '-e^{\\frac{1}{x}}+C' },
  { problem: '\\int x\\sqrt{x+1}\\,dx,\\quad\\text{let }u=x+1', answer: '\\frac{2}{5}(x+1)^{\\frac{5}{2}}-\\frac{2}{3}(x+1)^{\\frac{3}{2}}+C' },
  { problem: '\\int\\frac{x}{\\sqrt{x-1}}\\,dx,\\quad\\text{let }u=x-1', answer: '\\frac{2}{3}(x-1)^{\\frac{3}{2}}+2\\sqrt{x-1}+C' },
  { problem: '\\int\\frac{x}{(x-1)^2}\\,dx,\\quad\\text{let }u=x-1', answer: '\\ln(x-1)-\\frac{1}{x-1}+C' },
  { problem: '\\int\\frac{x-2}{x+2}\\,dx,\\quad\\text{let }u=x+2', answer: 'x-4\\ln(x+2)+C' },
  { problem: '\\int\\frac{2x+1}{\\sqrt{2x-1}}\\,dx,\\quad\\text{let }u=2x-1', answer: '\\frac{1}{3}(2x-1)^{\\frac{3}{2}}+2\\sqrt{2x-1}+C' },
  { problem: '\\int\\frac{1}{x\\ln x}\\,dx,\\quad\\text{let }u=\\ln x', answer: '\\ln(\\ln x)+C' },
  { problem: '\\int\\frac{e^{2x}}{\\sqrt{1+e^{2x}}}\\,dx,\\quad\\text{let }u=1+e^{2x}', answer: '\\sqrt{1+e^{2x}}+C' },
  { problem: '\\int_0^4\\frac{e^{\\sqrt{x}}}{4\\sqrt{x}}\\,dx,\\quad\\text{let }u=\\sqrt{x}', answer: '\\frac{1}{2}(e^2-1)' },
  { problem: '\\int_0^1\\frac{(\\sin^{-1}x)^3}{\\sqrt{1-x^2}}\\,dx,\\quad\\text{let }u=\\sin^{-1}x', answer: '\\frac{\\pi^4}{64}' },
  { problem: '\\int_0^2\\frac{x+1}{(x^2+2x)^{\\frac{1}{3}}}\\,dx,\\quad\\text{let }u=x^2+2x', answer: '3' },
  { problem: '\\int_{\\frac{\\pi}{4}}^{\\frac{\\pi}{3}}\\frac{\\sec^2 x}{\\tan x}\\,dx,\\quad\\text{let }u=\\tan x', answer: '\\frac{1}{2}\\ln 3' },
  { problem: '\\int_0^{\\frac{\\pi}{6}}\\frac{\\cos x}{1+\\sin x}\\,dx,\\quad\\text{let }u=1+\\sin x', answer: '\\ln\\left(\\frac{3}{2}\\right)' },
  { problem: '\\int_0^{\\frac{\\pi}{2}}\\cos^3 x\\,dx,\\quad\\text{let }u=\\sin x', answer: '\\frac{2}{3}' },
  { problem: '\\int_0^{\\frac{\\pi}{2}}\\frac{\\sin(2x)}{1+\\sin^2 x}\\,dx,\\quad\\text{let }u=1+\\sin^2 x', answer: '\\ln 2' },
  { problem: '\\int_0^1 x(x+1)^3\\,dx,\\quad\\text{let }u=x+1', answer: '\\frac{49}{20}' },
  { problem: '\\int_0^{\\frac{1}{2}}\\frac{1+x}{1-x}\\,dx,\\quad\\text{let }u=1-x', answer: '2\\ln 2-\\frac{1}{2}' },
  { problem: '\\int_0^1\\frac{3x}{\\sqrt{3x+1}}\\,dx,\\quad\\text{let }u=3x+1', answer: '\\frac{8}{9}' },
  { problem: '\\int_0^1\\frac{2-x}{(2+x)^3}\\,dx,\\quad\\text{let }u=2+x', answer: '\\frac{1}{9}' },
  { problem: '\\int x\\sqrt{2x+1}\\,dx,\\quad\\text{let }u=2x+1', answer: '\\frac{1}{10}(2x+1)^{\\frac{5}{2}}-\\frac{1}{6}(2x+1)^{\\frac{3}{2}}+C' },
  { problem: '\\int x(x-2)^4\\,dx,\\quad\\text{let }u=x-2', answer: '\\frac{1}{6}(x-2)^6+\\frac{2}{5}(x-2)^5+C' },
  { problem: '\\int\\frac{x}{\\sqrt{x+2}}\\,dx,\\quad\\text{let }u=x+2', answer: '\\frac{2}{3}(x+2)^{\\frac{3}{2}}-4\\sqrt{x+2}+C' },
  { problem: '\\int x\\sqrt{1-x}\\,dx,\\quad\\text{let }u=1-x', answer: '-\\frac{2}{3}(1-x)^{\\frac{3}{2}}+\\frac{2}{5}(1-x)^{\\frac{5}{2}}+C' },
  { problem: '\\int\\tan x\\,dx,\\quad\\text{let }u=\\cos x', answer: '-\\ln(\\cos x)+C' },
  { problem: '\\int\\cot x\\,dx,\\quad\\text{let }u=\\sin x', answer: '\\ln(\\sin x)+C' },
  { problem: '\\int\\sin^3 x\\,dx,\\quad\\text{let }u=\\cos x', answer: '-\\cos x+\\frac{1}{3}\\cos^3 x+C' },
  { problem: '\\int\\frac{2x+3}{x^2+3x+1}\\,dx,\\quad\\text{let }u=x^2+3x+1', answer: '\\ln(x^2+3x+1)+C' },
  { problem: '\\int\\frac{x}{x^2+4}\\,dx,\\quad\\text{let }u=x^2+4', answer: '\\frac{1}{2}\\ln(x^2+4)+C' },
  { problem: '\\int_1^2 x\\sqrt{x-1}\\,dx,\\quad\\text{let }u=x-1', answer: '\\frac{16}{15}' },
], { mode: 'integral', toleranceDp: 4 });
