import { BaseLevel } from './BaseLevel.js';

export default new BaseLevel('inverseTrigDiffMedium', 'Differentiating Inverse Trig — Medium', [
  { problem: '\\frac{d}{dx}(\\sin^{-1}(3x+1))', answer: '\\frac{3}{\\sqrt{1-(3x+1)^2}}' },
  { problem: '\\frac{d}{dx}(\\sin^{-1}(x^2))', answer: '\\frac{2x}{\\sqrt{1-x^4}}' },
  { problem: '\\frac{d}{dx}(\\tan^{-1}(x^3))', answer: '\\frac{3x^2}{1+x^6}' },
  { problem: '\\frac{d}{dx}(\\tan^{-1}(x+2))', answer: '\\frac{1}{x^2+4x+5}' },
  { problem: '\\frac{d}{dx}(\\cos^{-1}(1-x))', answer: '\\frac{1}{\\sqrt{2x-x^2}}' },
  { problem: '\\frac{d}{dx}(x\\sin^{-1}x)', answer: '\\sin^{-1}x+\\frac{x}{\\sqrt{1-x^2}}' },
  { problem: '\\frac{d}{dx}((1+x^2)\\tan^{-1}x)', answer: '2x\\tan^{-1}x+1' },
  { problem: '\\frac{d}{dx}\\left(\\tan^{-1}\\left(\\frac{1}{x}\\right)\\right)', answer: '-\\frac{1}{1+x^2}' },
  { problem: '\\frac{d}{dx}(\\sin^{-1}(x^3))', answer: '\\frac{3x^2}{\\sqrt{1-x^6}}' },
  { problem: '\\frac{d}{dx}(\\cos^{-1}(x^2))', answer: '-\\frac{2x}{\\sqrt{1-x^4}}' },
  { problem: '\\frac{d}{dx}(\\tan^{-1}(x^2))', answer: '\\frac{2x}{1+x^4}' },
  { problem: '\\frac{d}{dx}(\\sin^{-1}(2x^2))', answer: '\\frac{4x}{\\sqrt{1-4x^4}}' },
  { problem: '\\frac{d}{dx}(\\cos^{-1}(x^3))', answer: '-\\frac{3x^2}{\\sqrt{1-x^6}}' },
  { problem: '\\frac{d}{dx}(\\tan^{-1}(2x^2))', answer: '\\frac{4x}{1+4x^4}' },
  { problem: '\\frac{d}{dx}(\\sin^{-1}(x^4))', answer: '\\frac{4x^3}{\\sqrt{1-x^8}}' },
  { problem: '\\frac{d}{dx}(\\tan^{-1}(5x^2))', answer: '\\frac{10x}{1+25x^4}' },
  { problem: '\\frac{d}{dx}(\\cos^{-1}(2x^2))', answer: '-\\frac{4x}{\\sqrt{1-4x^4}}' },
  { problem: '\\frac{d}{dx}(\\sin^{-1}(2x-1))', answer: '\\frac{1}{\\sqrt{x-x^2}}' },
  { problem: '\\frac{d}{dx}(\\tan^{-1}(2x+1))', answer: '\\frac{1}{2x^2+2x+1}' },
  { problem: '\\frac{d}{dx}(\\tan^{-1}(3x-1))', answer: '\\frac{3}{9x^2-6x+2}' },
  { problem: '\\frac{d}{dx}(\\tan^{-1}(x-3))', answer: '\\frac{1}{x^2-6x+10}' },
  { problem: '\\frac{d}{dx}(\\cos^{-1}(2-x))', answer: '\\frac{1}{\\sqrt{4x-x^2-3}}' },
  { problem: '\\frac{d}{dx}(\\sin^{-1}(4x-1))', answer: '\\frac{4}{\\sqrt{1-(4x-1)^2}}' },
  { problem: '\\frac{d}{dx}\\left(\\tan^{-1}\\left(\\frac{2}{x}\\right)\\right)', answer: '-\\frac{2}{x^2+4}' },
  { problem: '\\frac{d}{dx}\\left(\\tan^{-1}\\left(\\frac{3}{x}\\right)\\right)', answer: '-\\frac{3}{x^2+9}' },
  { problem: '\\frac{d}{dx}(x\\tan^{-1}x)', answer: '\\tan^{-1}x+\\frac{x}{1+x^2}' },
  { problem: '\\frac{d}{dx}(2x\\tan^{-1}x)', answer: '2\\tan^{-1}x+\\frac{2x}{1+x^2}' },
  { problem: '\\frac{d}{dx}(x^2\\sin^{-1}x)', answer: '2x\\sin^{-1}x+\\frac{x^2}{\\sqrt{1-x^2}}' },
  { problem: '\\frac{d}{dx}(x\\sin^{-1}(2x))', answer: '\\sin^{-1}(2x)+\\frac{2x}{\\sqrt{1-4x^2}}' },
  { problem: '\\frac{d}{dx}((x-1)\\tan^{-1}x)', answer: '\\tan^{-1}x+\\frac{x-1}{1+x^2}' },
], { mode: 'derivative', toleranceDp: 4 });
