import { BaseLevel } from './BaseLevel.js';

export default new BaseLevel('logarithmicDiffHard', 'Logarithmic Functions — Hard', [
  { problem: '\\frac{d}{dx}((\\ln x)^3)', answer: '\\frac{3(\\ln x)^2}{x}' },
  { problem: '\\frac{d}{dx}\\left(\\ln\\left(\\frac{1+x}{1-x}\\right)\\right)', answer: '\\frac{1}{1+x}+\\frac{1}{1-x}' },
  { problem: '\\frac{d}{dx}\\left(\\ln(\\sqrt{2-x})\\right)', answer: '-\\frac{1}{2(2-x)}' },
  { problem: '\\frac{d}{dx}((\\ln x)^4)', answer: '\\frac{4(\\ln x)^3}{x}' },
  { problem: '\\frac{d}{dx}((2\\ln x-3)^4)', answer: '\\frac{8(2\\ln x-3)^3}{x}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{1}{\\ln x}\\right)', answer: '-\\frac{1}{x(\\ln x)^2}' },
  { problem: '\\frac{d}{dx}(\\ln(\\ln x))', answer: '\\frac{1}{x\\ln x}' },
  { problem: '\\frac{d}{dx}((\\ln x+x)^5)', answer: '\\frac{5(1+x)(\\ln x+x)^4}{x}' },
  { problem: '\\frac{d}{dx}((x^2+\\ln x)^6)', answer: '6\\left(2x+\\frac{1}{x}\\right)(x^2+\\ln x)^5' },
  { problem: '\\frac{d}{dx}\\left(\\ln\\left(\\frac{4x+1}{2x-7}\\right)\\right)', answer: '-\\frac{30}{(4x+1)(2x-7)}' },
  { problem: '\\frac{d}{dx}((\\ln x)^5)', answer: '\\frac{5(\\ln x)^4}{x}' },
  { problem: '\\frac{d}{dx}((3\\ln x+1)^4)', answer: '\\frac{12(3\\ln x+1)^3}{x}' },
  { problem: '\\frac{d}{dx}((\\ln x-x)^4)', answer: '4\\left(\\frac{1}{x}-1\\right)(\\ln x-x)^3' },
  { problem: '\\frac{d}{dx}(\\sqrt{\\ln x})', answer: '\\frac{1}{2x\\sqrt{\\ln x}}' },
  { problem: '\\frac{d}{dx}(\\sqrt{\\ln(2x)})', answer: '\\frac{1}{2x\\sqrt{\\ln(2x)}}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{1}{\\sqrt{\\ln x}}\\right)', answer: '-\\frac{1}{2x(\\ln x)^{3/2}}' },
  { problem: '\\frac{d}{dx}((\\ln(x^2))^3)', answer: '\\frac{6(\\ln(x^2))^2}{x}' },
  { problem: '\\frac{d}{dx}\\left(\\ln\\left(\\frac{1-x}{1+x}\\right)\\right)', answer: '-\\frac{2}{1-x^2}' },
  { problem: '\\frac{d}{dx}\\left(\\ln\\sqrt{x^2+1}\\right)', answer: '\\frac{x}{x^2+1}' },
  { problem: '\\frac{d}{dx}\\left(\\ln\\sqrt{\\frac{x}{1+x}}\\right)', answer: '\\frac{1}{2x(1+x)}' },
  { problem: '\\frac{d}{dx}\\left(\\ln\\left(\\frac{x^2-1}{x^2+1}\\right)\\right)', answer: '\\frac{4x}{x^4-1}' },
  { problem: '\\frac{d}{dx}((\\ln(2x+1))^3)', answer: '\\frac{6(\\ln(2x+1))^2}{2x+1}' },
  { problem: '\\frac{d}{dx}((\\ln(x^2+1))^2)', answer: '\\frac{4x\\ln(x^2+1)}{x^2+1}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{1}{\\ln(2x)}\\right)', answer: '-\\frac{1}{x(\\ln(2x))^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{1}{(\\ln x)^2}\\right)', answer: '-\\frac{2}{x(\\ln x)^3}' },
  { problem: '\\frac{d}{dx}\\left(\\ln\\left(\\frac{x}{x+2}\\right)\\right)', answer: '\\frac{2}{x^2+2x}' },
  { problem: '\\frac{d}{dx}(\\ln(x^3+x))', answer: '\\frac{3x^2+1}{x^3+x}' },
  { problem: '\\frac{d}{dx}((\\ln(3x-2))^4)', answer: '\\frac{12(\\ln(3x-2))^3}{3x-2}' },
  { problem: '\\frac{d}{dx}\\left(\\ln\\left(\\frac{(x+1)^2}{x-1}\\right)\\right)', answer: '\\frac{x-3}{x^2-1}' },
  { problem: '\\frac{d}{dx}((\\ln x)^{1/3})', answer: '\\frac{1}{3x(\\ln x)^{2/3}}' },
], { mode: 'derivative', toleranceDp: 2 });
