import { BaseLevel } from './BaseLevel.js';

export default new BaseLevel('logarithmicDiffRulesEasy', 'Logarithmic with Rules — Easy', [
  { problem: '\\frac{d}{dx}(x^3\\ln x)', answer: 'x^2(3\\ln x+1)' },
  { problem: '\\frac{d}{dx}(x^4\\ln x)', answer: 'x^3(4\\ln x+1)' },
  { problem: '\\frac{d}{dx}(x\\ln x)', answer: '1+\\ln x' },
  { problem: '\\frac{d}{dx}((2x+1)\\ln x)', answer: '2\\ln x+\\frac{2x+1}{x}' },
  { problem: '\\frac{d}{dx}((x+3)\\ln(x+3))', answer: '\\ln(x+3)+1' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\ln x}{x}\\right)', answer: '\\frac{1-\\ln x}{x^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\ln x}{x^2}\\right)', answer: '\\frac{1-2\\ln x}{x^3}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x}{\\ln x}\\right)', answer: '\\frac{\\ln x-1}{(\\ln x)^2}' },
  { problem: '\\frac{d}{dx}(x\\ln x-x)', answer: '\\ln x' },
  { problem: '\\frac{d}{dx}(x^2\\ln x)', answer: 'x(1+2\\ln x)' },
  { problem: '\\frac{d}{dx}(x^5\\ln x)', answer: 'x^4(5\\ln x+1)' },
  { problem: '\\frac{d}{dx}(x^6\\ln x)', answer: 'x^5(6\\ln x+1)' },
  { problem: '\\frac{d}{dx}((x-1)\\ln x)', answer: '\\ln x+\\frac{x-1}{x}' },
  { problem: '\\frac{d}{dx}((3x+2)\\ln x)', answer: '3\\ln x+\\frac{3x+2}{x}' },
  { problem: '\\frac{d}{dx}((x-2)\\ln(x-2))', answer: '\\ln(x-2)+1' },
  { problem: '\\frac{d}{dx}((2x+1)\\ln(2x+1))', answer: '2(\\ln(2x+1)+1)' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\ln x}{x^3}\\right)', answer: '\\frac{1-3\\ln x}{x^4}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\ln x}{x^4}\\right)', answer: '\\frac{1-4\\ln x}{x^5}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x^2}{\\ln x}\\right)', answer: '\\frac{x(2\\ln x-1)}{(\\ln x)^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x^3}{\\ln x}\\right)', answer: '\\frac{x^2(3\\ln x-1)}{(\\ln x)^2}' },
  { problem: '\\frac{d}{dx}(2x\\ln x)', answer: '2(1+\\ln x)' },
  { problem: '\\frac{d}{dx}(3x^2\\ln x)', answer: '3x(1+2\\ln x)' },
  { problem: '\\frac{d}{dx}(x^2\\ln(x^2))', answer: '2x(\\ln(x^2)+1)' },
  { problem: '\\frac{d}{dx}((2x+3)\\ln(2x+3))', answer: '2(\\ln(2x+3)+1)' },
  { problem: '\\frac{d}{dx}((x+1)^2\\ln(x+1))', answer: '(x+1)(2\\ln(x+1)+1)' },
  { problem: '\\frac{d}{dx}((x^2-1)\\ln x)', answer: '2x\\ln x+\\frac{x^2-1}{x}' },
  { problem: '\\frac{d}{dx}((x^3+x)\\ln x)', answer: '(3x^2+1)\\ln x+x^2+1' },
  { problem: '\\frac{d}{dx}\\left(\\frac{3x}{\\ln x}\\right)', answer: '\\frac{3(\\ln x-1)}{(\\ln x)^2}' },
  { problem: '\\frac{d}{dx}\\left(x^5\\ln x-\\frac{x^5}{5}\\right)', answer: '5x^4\\ln x' },
  { problem: '\\frac{d}{dx}\\left(x^4\\ln x-\\frac{x^4}{4}\\right)', answer: '4x^3\\ln x' },
], { mode: 'derivative', toleranceDp: 2 });
