import { BaseLevel } from './BaseLevel.js';

export default new BaseLevel('logarithmicDiffEasy', 'Logarithmic Functions — Easy', [
  { problem: '\\frac{d}{dx}(2\\ln x)', answer: '\\frac{2}{x}' },
  { problem: '\\frac{d}{dx}(x^2+\\ln x)', answer: '2x+\\frac{1}{x}' },
  { problem: '\\frac{d}{dx}(5x^2-3\\ln x)', answer: '10x-\\frac{3}{x}' },
  { problem: '\\frac{d}{dx}(5\\ln x)', answer: '\\frac{5}{x}' },
  { problem: '\\frac{d}{dx}(-5\\ln x)', answer: '-\\frac{5}{x}' },
  { problem: '\\frac{d}{dx}(x-5\\ln x)', answer: '1-\\frac{5}{x}' },
  { problem: '\\frac{d}{dx}(3-5\\ln x)', answer: '-\\frac{5}{x}' },
  { problem: '\\frac{d}{dx}(x^3-5\\ln x)', answer: '3x^2-\\frac{5}{x}' },
  { problem: '\\frac{d}{dx}(7x^2+12\\ln x)', answer: '14x+\\frac{12}{x}' },
  { problem: '\\frac{d}{dx}(\\ln(7x))', answer: '\\frac{1}{x}' },
  { problem: '\\frac{d}{dx}(\\ln(2x))', answer: '\\frac{1}{x}' },
  { problem: '\\frac{d}{dx}(\\ln(5x))', answer: '\\frac{1}{x}' },
  { problem: '\\frac{d}{dx}(\\ln 7+\\ln x)', answer: '\\frac{1}{x}' },
  { problem: '\\frac{d}{dx}(4\\ln(7x))', answer: '\\frac{4}{x}' },
  { problem: '\\frac{d}{dx}(3\\ln(5x))', answer: '\\frac{3}{x}' },
  { problem: '\\frac{d}{dx}(4\\ln(6x))', answer: '\\frac{4}{x}' },
  { problem: '\\frac{d}{dx}(\\ln(x+2))', answer: '\\frac{1}{x+2}' },
  { problem: '\\frac{d}{dx}(\\ln(x-3))', answer: '\\frac{1}{x-3}' },
  { problem: '\\frac{d}{dx}(\\ln(3x+4))', answer: '\\frac{3}{3x+4}' },
  { problem: '\\frac{d}{dx}(\\ln(2x-1))', answer: '\\frac{2}{2x-1}' },
  { problem: '\\frac{d}{dx}(\\ln(-4x+1))', answer: '-\\frac{4}{-4x+1}' },
  { problem: '\\frac{d}{dx}(\\ln(-3x+4))', answer: '-\\frac{3}{-3x+4}' },
  { problem: '\\frac{d}{dx}(5\\ln(3x-2))', answer: '\\frac{15}{3x-2}' },
  { problem: '\\frac{d}{dx}(\\ln(4x+3))', answer: '\\frac{4}{4x+3}' },
  { problem: '\\frac{d}{dx}(6\\ln(2x+9))', answer: '\\frac{12}{2x+9}' },
  { problem: '\\frac{d}{dx}(2+\\ln x)', answer: '\\frac{1}{x}' },
  { problem: '\\frac{d}{dx}(5-\\ln(x+1))', answer: '-\\frac{1}{x+1}' },
  { problem: '\\frac{d}{dx}(x+4\\ln x)', answer: '1+\\frac{4}{x}' },
  { problem: '\\frac{d}{dx}(2x^4+1+3\\ln x)', answer: '8x^3+\\frac{3}{x}' },
  { problem: '\\frac{d}{dx}(\\ln(2x-1)+3x^2)', answer: '\\frac{2}{2x-1}+6x' },
  { problem: '\\frac{d}{dx}(x^3-3x+4+\\ln(5x-7))', answer: '3x^2-3+\\frac{5}{5x-7}' },
  { problem: '\\frac{d}{dx}(\\log_5 x)', answer: '\\frac{1}{x\\ln 5}' },
  { problem: '\\frac{d}{dx}(\\log_8 x)', answer: '\\frac{1}{x\\ln 8}' },
  { problem: '\\frac{d}{dx}(\\log_{52} x)', answer: '\\frac{1}{x\\ln 52}' },
  { problem: '\\frac{d}{dx}(\\log_{11} x)', answer: '\\frac{1}{x\\ln 11}' },
  { problem: '\\frac{d}{dx}(\\log_{62} x)', answer: '\\frac{1}{x\\ln 62}' },
  { problem: '\\frac{d}{dx}\\left(\\log_{\\frac{3}{4}} x\\right)', answer: '\\frac{1}{x\\ln\\left(\\frac{3}{4}\\right)}' },
  { problem: '\\frac{d}{dx}(7\\log_2 x)', answer: '\\frac{7}{x\\ln 2}' },
  { problem: '\\frac{d}{dx}(11\\log_5 x)', answer: '\\frac{11}{x\\ln 5}' },
  { problem: '\\frac{d}{dx}(\\log_5(2x))', answer: '\\frac{1}{x\\ln 5}' },
  { problem: '\\frac{d}{dx}(\\log_3(7x))', answer: '\\frac{1}{x\\ln 3}' },
  { problem: '\\frac{d}{dx}(\\log_3(7x-3))', answer: '\\frac{7}{(7x-3)\\ln 3}' },
  { problem: '\\frac{d}{dx}(\\log_5(2x+7))', answer: '\\frac{2}{(2x+7)\\ln 5}' },
  { problem: '\\frac{d}{dx}(\\log_2 x)', answer: '\\frac{1}{x\\ln 2}' },
  { problem: '\\frac{d}{dx}(\\log_{10} x)', answer: '\\frac{1}{x\\ln 10}' },
  { problem: '\\frac{d}{dx}(3\\log_5 x)', answer: '\\frac{3}{x\\ln 5}' },
  { problem: '\\frac{d}{dx}(\\log_3 x)', answer: '\\frac{1}{x\\ln 3}' },
  { problem: '\\frac{d}{dx}(\\log_7 x)', answer: '\\frac{1}{x\\ln 7}' },
  { problem: '\\frac{d}{dx}(5\\log_6 x)', answer: '\\frac{5}{x\\ln 6}' },
  { problem: '\\frac{d}{dx}(x+\\ln x)', answer: '1+\\frac{1}{x}' },
  { problem: '\\frac{d}{dx}(1-\\ln(3x))', answer: '-\\frac{1}{x}' },
], { mode: 'derivative', toleranceDp: 2 });
