import { BaseLevel } from './BaseLevel.js';

export default new BaseLevel('logarithmicDiffMedium', 'Logarithmic Functions — Medium', [
  { problem: '\\frac{d}{dx}(\\ln(x^2))', answer: '\\frac{2}{x}' },
  { problem: '\\frac{d}{dx}(\\ln(3x^5+7x))', answer: '\\frac{15x^4+7}{3x^5+7x}' },
  { problem: '\\frac{d}{dx}(\\ln(5x^2))', answer: '\\frac{2}{x}' },
  { problem: '\\frac{d}{dx}\\left(\\ln\\left(\\frac{5}{x}\\right)\\right)', answer: '-\\frac{1}{x}' },
  { problem: '\\frac{d}{dx}\\left(\\ln(\\sqrt{x})\\right)', answer: '\\frac{1}{2x}' },
  { problem: '\\frac{d}{dx}(\\ln(11x^3-7x^2))', answer: '\\frac{33x^2-14x}{11x^3-7x^2}' },
  { problem: '\\frac{d}{dx}(\\ln(7x^2))', answer: '\\frac{2}{x}' },
  { problem: '\\frac{d}{dx}(\\ln((3x-7)^5))', answer: '\\frac{15}{3x-7}' },
  { problem: '\\frac{d}{dx}(\\ln(x^3))', answer: '\\frac{3}{x}' },
  { problem: '\\frac{d}{dx}(\\ln(-2x-7))', answer: '\\frac{2}{2x+7}' },
  { problem: '\\frac{d}{dx}(3\\ln(2x+4))', answer: '\\frac{3}{x+2}' },
  { problem: '\\frac{d}{dx}\\left(\\ln\\left(\\frac{x}{2}\\right)\\right)', answer: '\\frac{1}{x}' },
  { problem: '\\frac{d}{dx}\\left(\\ln\\left(\\frac{x}{3}\\right)\\right)', answer: '\\frac{1}{x}' },
  { problem: '\\frac{d}{dx}\\left(3\\ln\\left(\\frac{x}{5}\\right)\\right)', answer: '\\frac{3}{x}' },
  { problem: '\\frac{d}{dx}\\left(-6\\ln\\left(\\frac{x}{5}\\right)\\right)', answer: '-\\frac{6}{x}' },
  { problem: '\\frac{d}{dx}\\left(x+\\ln\\left(\\frac{x}{3}\\right)\\right)', answer: '1+\\frac{1}{x}' },
  { problem: '\\frac{d}{dx}\\left(4x^3-\\ln\\left(\\frac{x}{5}\\right)\\right)', answer: '12x^2-\\frac{1}{x}' },
  { problem: '\\frac{d}{dx}(\\ln(x^2+1))', answer: '\\frac{2x}{x^2+1}' },
  { problem: '\\frac{d}{dx}(\\ln(2-x^2))', answer: '\\frac{-2x}{2-x^2}' },
  { problem: '\\frac{d}{dx}(\\ln(x^2+3x+2))', answer: '\\frac{2x+3}{x^2+3x+2}' },
  { problem: '\\frac{d}{dx}(\\ln(1+2x^3))', answer: '\\frac{6x^2}{1+2x^3}' },
  { problem: '\\frac{d}{dx}(x+3-\\ln(x^2+x))', answer: '1-\\frac{2x+1}{x^2+x}' },
  { problem: '\\frac{d}{dx}(x^2+\\ln(x^3-x))', answer: '2x+\\frac{3x^2-1}{x^3-x}' },
  { problem: '\\frac{d}{dx}(4x^3-\\ln(2x^2-3x+1))', answer: '12x^2-\\frac{4x-3}{2x^2-3x+1}' },
  { problem: '\\frac{d}{dx}(\\log_7(x^3-7x))', answer: '\\frac{3x^2-7}{(x^3-7x)\\ln 7}' },
  { problem: '\\frac{d}{dx}(\\log_{11}(x^4))', answer: '\\frac{4}{x\\ln 11}' },
  { problem: '\\frac{d}{dx}(\\log_{12}(3x^2+5))', answer: '\\frac{6x}{(3x^2+5)\\ln 12}' },
  { problem: '\\frac{d}{dx}\\left(\\log_7(\\sqrt{x})\\right)', answer: '\\frac{1}{2x\\ln 7}' },
  { problem: '\\frac{d}{dx}\\left(\\log_{12}\\left(\\frac{1}{x}\\right)\\right)', answer: '-\\frac{1}{x\\ln 12}' },
  { problem: '\\frac{d}{dx}(\\ln(5x^3))', answer: '\\frac{3}{x}' },
  { problem: '\\frac{d}{dx}\\left(\\ln(\\sqrt[3]{x})\\right)', answer: '\\frac{1}{3x}' },
  { problem: '\\frac{d}{dx}\\left(\\ln\\left(\\frac{3}{x}\\right)\\right)', answer: '-\\frac{1}{x}' },
  { problem: '\\frac{d}{dx}(\\ln(x^{-3}))', answer: '-\\frac{3}{x}' },
  { problem: '\\frac{d}{dx}(\\ln(x^{-2}))', answer: '-\\frac{2}{x}' },
  { problem: '\\frac{d}{dx}\\left(\\ln(\\sqrt{x})+1\\right)', answer: '\\frac{1}{2x}' },
  { problem: '\\frac{d}{dx}(\\ln(3x+1))', answer: '\\frac{3}{3x+1}' },
  { problem: '\\frac{d}{dx}(\\ln(x^2-4))', answer: '\\frac{2x}{x^2-4}' },
  { problem: '\\frac{d}{dx}(\\ln(5x^3+3x-9))', answer: '\\frac{15x^2+3}{5x^3+3x-9}' },
  { problem: '\\frac{d}{dx}(3x^2+5x-5+\\ln(4x))', answer: '6x+5+\\frac{1}{x}' },
  { problem: '\\frac{d}{dx}(\\ln(8x-9)+2)', answer: '\\frac{8}{8x-9}' },
  { problem: '\\frac{d}{dx}((1+\\ln x)^5)', answer: '\\frac{5(1+\\ln x)^4}{x}' },
  { problem: '\\frac{d}{dx}((\\ln x-x)^9)', answer: '9\\left(\\frac{1}{x}-1\\right)(\\ln x-x)^8' },
  { problem: '\\frac{d}{dx}(5(\\ln x)^2)', answer: '\\frac{10\\ln x}{x}' },
  { problem: '\\frac{d}{dx}(x+\\log_3 x)', answer: '1+\\frac{1}{x\\ln 3}' },
], { mode: 'derivative', toleranceDp: 2 });
