import { BaseLevel } from './BaseLevel.js';

export default new BaseLevel('sinCosSquaredIntEasy', 'sin and cos Squared Integration — Easy', [
  { problem: '\\int\\sin^2 x\\,dx', answer: '\\frac{x}{2}-\\frac{\\sin(2x)}{4}+C' },
  { problem: '\\int\\sin^2(2x)\\,dx', answer: '\\frac{x}{2}-\\frac{\\sin(4x)}{8}+C' },
  { problem: '\\int\\sin^2(3x)\\,dx', answer: '\\frac{x}{2}-\\frac{\\sin(6x)}{12}+C' },
  { problem: '\\int\\sin^2(4x)\\,dx', answer: '\\frac{x}{2}-\\frac{\\sin(8x)}{16}+C' },
  { problem: '\\int\\sin^2(5x)\\,dx', answer: '\\frac{x}{2}-\\frac{\\sin(10x)}{20}+C' },
  { problem: '\\int\\sin^2(6x)\\,dx', answer: '\\frac{x}{2}-\\frac{\\sin(12x)}{24}+C' },
  { problem: '\\int\\sin^2(7x)\\,dx', answer: '\\frac{x}{2}-\\frac{\\sin(14x)}{28}+C' },
  { problem: '\\int\\sin^2(8x)\\,dx', answer: '\\frac{x}{2}-\\frac{\\sin(16x)}{32}+C' },
  { problem: '\\int\\sin^2(9x)\\,dx', answer: '\\frac{x}{2}-\\frac{\\sin(18x)}{36}+C' },
  { problem: '\\int\\sin^2(10x)\\,dx', answer: '\\frac{x}{2}-\\frac{\\sin(20x)}{40}+C' },
  { problem: '\\int\\cos^2 x\\,dx', answer: '\\frac{x}{2}+\\frac{\\sin(2x)}{4}+C' },
  { problem: '\\int\\cos^2(2x)\\,dx', answer: '\\frac{x}{2}+\\frac{\\sin(4x)}{8}+C' },
  { problem: '\\int\\cos^2(3x)\\,dx', answer: '\\frac{x}{2}+\\frac{\\sin(6x)}{12}+C' },
  { problem: '\\int\\cos^2(4x)\\,dx', answer: '\\frac{x}{2}+\\frac{\\sin(8x)}{16}+C' },
  { problem: '\\int\\cos^2(5x)\\,dx', answer: '\\frac{x}{2}+\\frac{\\sin(10x)}{20}+C' },
  { problem: '\\int\\cos^2(6x)\\,dx', answer: '\\frac{x}{2}+\\frac{\\sin(12x)}{24}+C' },
  { problem: '\\int\\cos^2(7x)\\,dx', answer: '\\frac{x}{2}+\\frac{\\sin(14x)}{28}+C' },
  { problem: '\\int\\cos^2(8x)\\,dx', answer: '\\frac{x}{2}+\\frac{\\sin(16x)}{32}+C' },
  { problem: '\\int\\cos^2(9x)\\,dx', answer: '\\frac{x}{2}+\\frac{\\sin(18x)}{36}+C' },
  { problem: '\\int\\cos^2(10x)\\,dx', answer: '\\frac{x}{2}+\\frac{\\sin(20x)}{40}+C' },
  { problem: '\\int\\cos^2(12x)\\,dx', answer: '\\frac{x}{2}+\\frac{\\sin(24x)}{48}+C' },
  { problem: '\\int 2\\sin^2 x\\,dx', answer: 'x-\\frac{\\sin(2x)}{2}+C' },
  { problem: '\\int 3\\sin^2 x\\,dx', answer: '\\frac{3x}{2}-\\frac{3\\sin(2x)}{4}+C' },
  { problem: '\\int 6\\sin^2 x\\,dx', answer: '3x-\\frac{3\\sin(2x)}{2}+C' },
  { problem: '\\int 2\\sin^2(3x)\\,dx', answer: 'x-\\frac{\\sin(6x)}{6}+C' },
  { problem: '\\int 4\\sin^2(2x)\\,dx', answer: '2x-\\frac{\\sin(4x)}{2}+C' },
  { problem: '\\int 3\\cos^2 x\\,dx', answer: '\\frac{3x}{2}+\\frac{3\\sin(2x)}{4}+C' },
  { problem: '\\int 4\\cos^2 x\\,dx', answer: '2x+\\sin(2x)+C' },
  { problem: '\\int 5\\cos^2 x\\,dx', answer: '\\frac{5x}{2}+\\frac{5\\sin(2x)}{4}+C' },
  { problem: '\\int 2\\cos^2(2x)\\,dx', answer: 'x+\\frac{\\sin(4x)}{4}+C' },
  { problem: '\\int 2\\cos^2(5x)\\,dx', answer: 'x+\\frac{\\sin(10x)}{10}+C' },
], { mode: 'integral', toleranceDp: 4 });
