import { BaseLevel } from './BaseLevel.js';

export default new BaseLevel('sinCosSquaredIntHard', 'sin and cos Squared Integration — Hard', [
  { problem: '\\int\\sin(3x)\\cos(2x)\\,dx', answer: '-\\frac{\\cos(5x)}{10}-\\frac{\\cos x}{2}+C' },
  { problem: '\\int\\cos(3x)\\sin x\\,dx', answer: '-\\frac{\\cos(4x)}{8}+\\frac{\\cos(2x)}{4}+C' },
  { problem: '\\int_0^{\\frac{\\pi}{4}}2\\cos(2x)\\cos x\\,dx', answer: '\\frac{2\\sqrt{2}}{3}' },
  { problem: '\\int_0^{\\frac{\\pi}{3}}\\sin(5x)\\sin(2x)\\,dx', answer: '-\\frac{\\sqrt{3}}{28}' },
  { problem: '\\int\\sin(2x)\\cos x\\,dx', answer: '-\\frac{\\cos(3x)}{6}-\\frac{\\cos x}{2}+C' },
  { problem: '\\int\\sin(4x)\\cos x\\,dx', answer: '-\\frac{\\cos(5x)}{10}-\\frac{\\cos(3x)}{6}+C' },
  { problem: '\\int\\sin(3x)\\cos x\\,dx', answer: '-\\frac{\\cos(4x)}{8}-\\frac{\\cos(2x)}{4}+C' },
  { problem: '\\int\\sin(5x)\\cos(2x)\\,dx', answer: '-\\frac{\\cos(7x)}{14}-\\frac{\\cos(3x)}{6}+C' },
  { problem: '\\int\\sin(4x)\\cos(2x)\\,dx', answer: '-\\frac{\\cos(6x)}{12}-\\frac{\\cos(2x)}{4}+C' },
  { problem: '\\int\\sin(5x)\\cos(3x)\\,dx', answer: '-\\frac{\\cos(8x)}{16}-\\frac{\\cos(2x)}{4}+C' },
  { problem: '\\int\\cos(3x)\\cos x\\,dx', answer: '\\frac{\\sin(2x)}{4}+\\frac{\\sin(4x)}{8}+C' },
  { problem: '\\int\\cos(2x)\\cos x\\,dx', answer: '\\frac{\\sin x}{2}+\\frac{\\sin(3x)}{6}+C' },
  { problem: '\\int\\cos(4x)\\cos(2x)\\,dx', answer: '\\frac{\\sin(2x)}{4}+\\frac{\\sin(6x)}{12}+C' },
  { problem: '\\int\\cos(5x)\\cos(2x)\\,dx', answer: '\\frac{\\sin(3x)}{6}+\\frac{\\sin(7x)}{14}+C' },
  { problem: '\\int\\cos(5x)\\cos(3x)\\,dx', answer: '\\frac{\\sin(2x)}{4}+\\frac{\\sin(8x)}{16}+C' },
  { problem: '\\int\\cos(4x)\\cos x\\,dx', answer: '\\frac{\\sin(3x)}{6}+\\frac{\\sin(5x)}{10}+C' },
  { problem: '\\int\\sin(3x)\\sin x\\,dx', answer: '\\frac{\\sin(2x)}{4}-\\frac{\\sin(4x)}{8}+C' },
  { problem: '\\int\\sin(2x)\\sin x\\,dx', answer: '\\frac{\\sin x}{2}-\\frac{\\sin(3x)}{6}+C' },
  { problem: '\\int\\sin(4x)\\sin(2x)\\,dx', answer: '\\frac{\\sin(2x)}{4}-\\frac{\\sin(6x)}{12}+C' },
  { problem: '\\int\\sin(5x)\\sin(2x)\\,dx', answer: '\\frac{\\sin(3x)}{6}-\\frac{\\sin(7x)}{14}+C' },
  { problem: '\\int\\sin(5x)\\sin(3x)\\,dx', answer: '\\frac{\\sin(2x)}{4}-\\frac{\\sin(8x)}{16}+C' },
  { problem: '\\int\\sin(4x)\\sin x\\,dx', answer: '\\frac{\\sin(3x)}{6}-\\frac{\\sin(5x)}{10}+C' },
  { problem: '\\int 2\\sin(3x)\\cos x\\,dx', answer: '-\\frac{\\cos(4x)}{4}-\\frac{\\cos(2x)}{2}+C' },
  { problem: '\\int 4\\cos(3x)\\cos x\\,dx', answer: '\\sin(2x)+\\frac{\\sin(4x)}{2}+C' },
  { problem: '\\int 2\\sin(2x)\\sin x\\,dx', answer: '\\sin x-\\frac{\\sin(3x)}{3}+C' },
  { problem: '\\int_0^{\\frac{\\pi}{2}}\\sin(3x)\\cos x\\,dx', answer: '\\frac{1}{2}' },
  { problem: '\\int_0^{\\frac{\\pi}{2}}\\sin(2x)\\sin x\\,dx', answer: '\\frac{2}{3}' },
  { problem: '\\int_0^{\\frac{\\pi}{4}}\\cos(3x)\\cos x\\,dx', answer: '\\frac{1}{4}' },
  { problem: '\\int_0^{\\frac{\\pi}{6}}\\sin(2x)\\cos x\\,dx', answer: '\\frac{2}{3}-\\frac{\\sqrt{3}}{4}' },
  { problem: '\\int_0^{\\frac{\\pi}{3}}\\cos(2x)\\cos x\\,dx', answer: '\\frac{\\sqrt{3}}{4}' },
  { problem: '\\int_0^{\\frac{\\pi}{4}}\\sin(3x)\\sin x\\,dx', answer: '\\frac{1}{4}' },
], { mode: 'integral', toleranceDp: 4 });
