import { BaseLevel } from './BaseLevel.js';

export default new BaseLevel('sinCosSquaredIntMedium', 'sin and cos Squared Integration — Medium', [
  { problem: '\\int\\sin^2\\left(\\frac{x}{4}\\right)\\,dx', answer: '\\frac{x}{2}-\\sin\\left(\\frac{x}{2}\\right)+C' },
  { problem: '\\int\\cos^2\\left(\\frac{x}{2}\\right)\\,dx', answer: '\\frac{x}{2}+\\frac{\\sin x}{2}+C' },
  { problem: '\\int_0^{\\pi}\\sin^2 x\\,dx', answer: '\\frac{\\pi}{2}' },
  { problem: '\\int_0^{\\frac{\\pi}{4}}\\cos^2 x\\,dx', answer: '\\frac{\\pi+2}{8}' },
  { problem: '\\int_0^{\\frac{\\pi}{3}}\\cos^2 x\\,dx', answer: '\\frac{\\pi}{6}+\\frac{\\sqrt{3}}{8}' },
  { problem: '\\int\\sin^2\\left(\\frac{x}{2}\\right)\\,dx', answer: '\\frac{x}{2}-\\frac{\\sin x}{2}+C' },
  { problem: '\\int\\sin^2\\left(\\frac{x}{3}\\right)\\,dx', answer: '\\frac{x}{2}-\\frac{3}{4}\\sin\\left(\\frac{2x}{3}\\right)+C' },
  { problem: '\\int\\cos^2\\left(\\frac{x}{3}\\right)\\,dx', answer: '\\frac{x}{2}+\\frac{3}{4}\\sin\\left(\\frac{2x}{3}\\right)+C' },
  { problem: '\\int\\cos^2\\left(\\frac{x}{4}\\right)\\,dx', answer: '\\frac{x}{2}+\\sin\\left(\\frac{x}{2}\\right)+C' },
  { problem: '\\int\\sin^2\\left(\\frac{x}{5}\\right)\\,dx', answer: '\\frac{x}{2}-\\frac{5}{4}\\sin\\left(\\frac{2x}{5}\\right)+C' },
  { problem: '\\int\\cos^2\\left(\\frac{x}{5}\\right)\\,dx', answer: '\\frac{x}{2}+\\frac{5}{4}\\sin\\left(\\frac{2x}{5}\\right)+C' },
  { problem: '\\int\\sin^2\\left(\\frac{x}{6}\\right)\\,dx', answer: '\\frac{x}{2}-\\frac{3}{2}\\sin\\left(\\frac{x}{3}\\right)+C' },
  { problem: '\\int\\cos^2\\left(\\frac{x}{6}\\right)\\,dx', answer: '\\frac{x}{2}+\\frac{3}{2}\\sin\\left(\\frac{x}{3}\\right)+C' },
  { problem: '\\int_0^{\\pi}\\cos^2 x\\,dx', answer: '\\frac{\\pi}{2}' },
  { problem: '\\int_0^{\\frac{\\pi}{2}}\\sin^2 x\\,dx', answer: '\\frac{\\pi}{4}' },
  { problem: '\\int_0^{\\frac{\\pi}{2}}\\cos^2 x\\,dx', answer: '\\frac{\\pi}{4}' },
  { problem: '\\int_0^{\\frac{\\pi}{4}}\\sin^2 x\\,dx', answer: '\\frac{\\pi-2}{8}' },
  { problem: '\\int_0^{\\frac{\\pi}{3}}\\sin^2 x\\,dx', answer: '\\frac{\\pi}{6}-\\frac{\\sqrt{3}}{8}' },
  { problem: '\\int_0^{\\frac{\\pi}{6}}\\cos^2 x\\,dx', answer: '\\frac{\\pi}{12}+\\frac{\\sqrt{3}}{8}' },
  { problem: '\\int_0^{\\frac{\\pi}{6}}\\sin^2 x\\,dx', answer: '\\frac{\\pi}{12}-\\frac{\\sqrt{3}}{8}' },
  { problem: '\\int_0^{\\pi}\\sin^2(2x)\\,dx', answer: '\\frac{\\pi}{2}' },
  { problem: '\\int_0^{\\pi}\\cos^2(2x)\\,dx', answer: '\\frac{\\pi}{2}' },
  { problem: '\\int_0^{\\frac{\\pi}{2}}\\sin^2(2x)\\,dx', answer: '\\frac{\\pi}{4}' },
  { problem: '\\int_0^{2\\pi}\\sin^2 x\\,dx', answer: '\\pi' },
  { problem: '\\int_0^{2\\pi}\\cos^2 x\\,dx', answer: '\\pi' },
  { problem: '\\int_{\\frac{\\pi}{4}}^{\\frac{\\pi}{2}}\\cos^2 x\\,dx', answer: '\\frac{\\pi-2}{8}' },
  { problem: '\\int_{\\frac{\\pi}{4}}^{\\frac{\\pi}{2}}\\sin^2 x\\,dx', answer: '\\frac{\\pi+2}{8}' },
  { problem: '\\int_0^{\\pi}\\sin^2\\left(\\frac{x}{2}\\right)\\,dx', answer: '\\frac{\\pi}{2}' },
  { problem: '\\int_0^{\\frac{\\pi}{2}}\\cos^2(2x)\\,dx', answer: '\\frac{\\pi}{4}' },
  { problem: '\\int_0^{\\frac{\\pi}{8}}\\cos^2(2x)\\,dx', answer: '\\frac{\\pi+2}{16}' },
  { problem: '\\int_0^{\\frac{\\pi}{4}}\\cos^2(2x)\\,dx', answer: '\\frac{\\pi}{8}' },
], { mode: 'integral', toleranceDp: 4 });
