import { BaseLevel } from './BaseLevel.js';

export default new BaseLevel('trigDiffMedium', 'Trigonometric Functions — Medium', [
  { problem: '\\frac{d}{dx}(x^3+2x-\\sin x)', answer: '3x^2+2-\\cos x' },
  { problem: '\\frac{d}{dx}\\left(2x^4-\\frac{\\sin x}{5}\\right)', answer: '8x^3-\\frac{1}{5}\\cos x' },
  { problem: '\\frac{d}{dx}((4x)^2-13\\tan x)', answer: '32x-13\\sec^2 x' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\tan x}{51}+3e^x\\right)', answer: '\\frac{1}{51}\\sec^2 x+3e^x' },
  { problem: '\\frac{d}{dx}(\\sin(2x))', answer: '2\\cos(2x)' },
  { problem: '\\frac{d}{dx}(\\cos(2x))', answer: '-2\\sin(2x)' },
  { problem: '\\frac{d}{dx}(\\tan(7x))', answer: '7\\sec^2(7x)' },
  { problem: '\\frac{d}{dx}(5\\cos(8x+1))', answer: '-40\\sin(8x+1)' },
  { problem: '\\frac{d}{dx}(\\sin(x^2))', answer: '2x\\cos(x^2)' },
  { problem: '\\frac{d}{dx}\\left(\\sin\\left(x^2-\\frac{\\pi}{4}\\right)\\right)', answer: '2x\\cos\\left(x^2-\\frac{\\pi}{4}\\right)' },
  { problem: '\\frac{d}{dx}(\\cos(3x))', answer: '-3\\sin(3x)' },
  { problem: '\\frac{d}{dx}(\\tan(4x))', answer: '4\\sec^2(4x)' },
  { problem: '\\frac{d}{dx}(2\\sin(3x))', answer: '6\\cos(3x)' },
  { problem: '\\frac{d}{dx}(2\\tan(2x))', answer: '4\\sec^2(2x)' },
  { problem: '\\frac{d}{dx}(4\\cos(2x))', answer: '-8\\sin(2x)' },
  { problem: '\\frac{d}{dx}(-\\sin(2x))', answer: '-2\\cos(2x)' },
  { problem: '\\frac{d}{dx}(-\\cos(2x))', answer: '2\\sin(2x)' },
  { problem: '\\frac{d}{dx}(-\\tan(2x))', answer: '-2\\sec^2(2x)' },
  { problem: '\\frac{d}{dx}\\left(\\tan\\left(\\frac{x}{2}\\right)\\right)', answer: '\\frac{1}{2}\\sec^2\\left(\\frac{x}{2}\\right)' },
  { problem: '\\frac{d}{dx}\\left(\\cos\\left(\\frac{x}{2}\\right)\\right)', answer: '-\\frac{1}{2}\\sin\\left(\\frac{x}{2}\\right)' },
  { problem: '\\frac{d}{dx}\\left(\\sin\\left(\\frac{x}{3}\\right)\\right)', answer: '\\frac{1}{3}\\cos\\left(\\frac{x}{3}\\right)' },
  { problem: '\\frac{d}{dx}\\left(5\\tan\\left(\\frac{x}{5}\\right)\\right)', answer: '\\sec^2\\left(\\frac{x}{5}\\right)' },
  { problem: '\\frac{d}{dx}\\left(6\\cos\\left(\\frac{x}{3}\\right)\\right)', answer: '-2\\sin\\left(\\frac{x}{3}\\right)' },
  { problem: '\\frac{d}{dx}\\left(12\\sin\\left(\\frac{x}{4}\\right)\\right)', answer: '3\\cos\\left(\\frac{x}{4}\\right)' },
  { problem: '\\frac{d}{dx}(\\sin(2\\pi x))', answer: '2\\pi\\cos(2\\pi x)' },
  { problem: '\\frac{d}{dx}\\left(\\tan\\left(\\frac{\\pi x}{2}\\right)\\right)', answer: '\\frac{\\pi}{2}\\sec^2\\left(\\frac{\\pi x}{2}\\right)' },
  { problem: '\\frac{d}{dx}(3\\sin x+\\cos(5x))', answer: '3\\cos x-5\\sin(5x)' },
  { problem: '\\frac{d}{dx}(4\\sin(\\pi x)+3\\cos(\\pi x))', answer: '4\\pi\\cos(\\pi x)-3\\pi\\sin(\\pi x)' },
  { problem: '\\frac{d}{dx}(\\sin(2x-1))', answer: '2\\cos(2x-1)' },
  { problem: '\\frac{d}{dx}(\\tan(1+3x))', answer: '3\\sec^2(1+3x)' },
  { problem: '\\frac{d}{dx}(2\\cos(1-x))', answer: '2\\sin(1-x)' },
  { problem: '\\frac{d}{dx}(\\cos(5x+4))', answer: '-5\\sin(5x+4)' },
  { problem: '\\frac{d}{dx}(7\\sin(2-3x))', answer: '-21\\cos(2-3x)' },
  { problem: '\\frac{d}{dx}(10\\tan(10-x))', answer: '-10\\sec^2(10-x)' },
  { problem: '\\frac{d}{dx}\\left(6\\sin\\left(\\frac{x+1}{2}\\right)\\right)', answer: '3\\cos\\left(\\frac{x+1}{2}\\right)' },
  { problem: '\\frac{d}{dx}\\left(15\\cos\\left(\\frac{2x+1}{5}\\right)\\right)', answer: '-6\\sin\\left(\\frac{2x+1}{5}\\right)' },
  { problem: '\\frac{d}{dx}(\\sin(1-x^2))', answer: '-2x\\cos(1-x^2)' },
  { problem: '\\frac{d}{dx}(\\cos(x^3+1))', answer: '-3x^2\\sin(x^3+1)' },
  { problem: '\\frac{d}{dx}(\\cos^2 x)', answer: '-2\\cos x\\sin x' },
  { problem: '\\frac{d}{dx}(\\sin^3 x)', answer: '3\\sin^2 x\\cos x' },
  { problem: '\\frac{d}{dx}(\\tan^2 x)', answer: '2\\tan x\\sec^2 x' },
  { problem: '\\frac{d}{dx}(\\sin 4x)', answer: '4\\cos 4x' },
  { problem: '\\frac{d}{dx}(\\cos 3x)', answer: '-3\\sin 3x' },
  { problem: '\\frac{d}{dx}(\\tan 5x)', answer: '5\\sec^2 5x' },
  { problem: '\\frac{d}{dx}(\\tan(3x+1))', answer: '3\\sec^2(3x+1)' },
  { problem: '\\frac{d}{dx}(4\\cos(5x-3))', answer: '-20\\sin(5x-3)' },
  { problem: '\\frac{d}{dx}(\\sin 3x+\\cos 8x)', answer: '3\\cos 3x-8\\sin 8x' },
  { problem: '\\frac{d}{dx}(\\cos(-x))', answer: '\\sin(-x)' },
  { problem: '\\frac{d}{dx}(2\\cos(x^3))', answer: '-6x^2\\sin(x^3)' },
  { problem: '\\frac{d}{dx}(7\\tan(x^2+5))', answer: '14x\\sec^2(x^2+5)' },
  { problem: '\\frac{d}{dx}(\\tan(\\pi+x)+x^2)', answer: '\\sec^2(\\pi+x)+2x' },
  { problem: '\\frac{d}{dx}(e^x-\\cos 2x)', answer: 'e^x+2\\sin 2x' },
  { problem: '\\frac{d}{dx}(\\sin(1-\\ln x))', answer: '-\\frac{1}{x}\\cos(1-\\ln x)' },
  { problem: '\\frac{d}{dx}(\\sin(e^x+x))', answer: '(e^x+1)\\cos(e^x+x)' },
], { mode: 'derivative', toleranceDp: 2 });
