import { BaseLevel } from './BaseLevel.js';

export default new BaseLevel('trigDiffRulesMedium', 'Trigonometric with Rules — Medium', [
  { problem: '\\frac{d}{dx}(2x\\tan(2x))', answer: '2\\tan(2x)+4x\\sec^2(2x)' },
  { problem: '\\frac{d}{dx}(x^2\\cos(2x))', answer: '2x\\cos(2x)-2x^2\\sin(2x)' },
  { problem: '\\frac{d}{dx}(x^3\\sin(3x))', answer: '3x^2\\sin(3x)+3x^3\\cos(3x)' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x^2}{\\cos x}\\right)', answer: '\\frac{2x\\cos x+x^2\\sin x}{\\cos^2 x}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x}{1+\\sin x}\\right)', answer: '\\frac{1+\\sin x-x\\cos x}{(1+\\sin x)^2}' },
  { problem: '\\frac{d}{dx}(x\\tan x)', answer: 'x\\sec^2 x+\\tan x' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\sin x}{2x}\\right)', answer: '\\frac{x\\cos x-\\sin x}{2x^2}' },
  { problem: '\\frac{d}{dx}(x\\sin(2x))', answer: '\\sin(2x)+2x\\cos(2x)' },
  { problem: '\\frac{d}{dx}(x\\cos(3x))', answer: '\\cos(3x)-3x\\sin(3x)' },
  { problem: '\\frac{d}{dx}(x\\sin(4x))', answer: '\\sin(4x)+4x\\cos(4x)' },
  { problem: '\\frac{d}{dx}(x^2\\sin(3x))', answer: '2x\\sin(3x)+3x^2\\cos(3x)' },
  { problem: '\\frac{d}{dx}(x^2\\cos(4x))', answer: '2x\\cos(4x)-4x^2\\sin(4x)' },
  { problem: '\\frac{d}{dx}(x^2\\tan(2x))', answer: '2x\\tan(2x)+2x^2\\sec^2(2x)' },
  { problem: '\\frac{d}{dx}(x^3\\cos(2x))', answer: '3x^2\\cos(2x)-2x^3\\sin(2x)' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\sin(3x)}{x}\\right)', answer: '\\frac{3x\\cos(3x)-\\sin(3x)}{x^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\cos(2x)}{x}\\right)', answer: '-\\frac{2x\\sin(2x)+\\cos(2x)}{x^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x}{\\sin(2x)}\\right)', answer: '\\frac{\\sin(2x)-2x\\cos(2x)}{\\sin^2(2x)}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x}{\\cos(3x)}\\right)', answer: '\\frac{\\cos(3x)+3x\\sin(3x)}{\\cos^2(3x)}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x}{\\tan(4x)}\\right)', answer: '\\frac{\\tan(4x)-4x\\sec^2(4x)}{\\tan^2(4x)}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\cos(3x)}{x^2}\\right)', answer: '-\\frac{3x\\sin(3x)+2\\cos(3x)}{x^3}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x}{1+\\cos x}\\right)', answer: '\\frac{1+\\cos x+x\\sin x}{(1+\\cos x)^2}' },
  { problem: '\\frac{d}{dx}(x\\tan(3x))', answer: '\\tan(3x)+3x\\sec^2(3x)' },
  { problem: '\\frac{d}{dx}(x^3\\sin(2x))', answer: '3x^2\\sin(2x)+2x^3\\cos(2x)' },
  { problem: '\\frac{d}{dx}((x^2+1)\\sin(3x))', answer: '2x\\sin(3x)+3(x^2+1)\\cos(3x)' },
  { problem: '\\frac{d}{dx}((2x-1)\\cos(2x))', answer: '2\\cos(2x)-2(2x-1)\\sin(2x)' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x}{1-\\cos x}\\right)', answer: '\\frac{1-\\cos x-x\\sin x}{(1-\\cos x)^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\tan(2x)}{x}\\right)', answer: '\\frac{2x\\sec^2(2x)-\\tan(2x)}{x^2}' },
  { problem: '\\frac{d}{dx}(x\\sec(2x))', answer: '\\sec(2x)(1+2x\\tan(2x))' },
  { problem: '\\frac{d}{dx}(x\\cot(3x))', answer: '\\cot(3x)-3x\\csc^2(3x)' },
  { problem: '\\frac{d}{dx}((x^2-1)\\sin(2x))', answer: '2x\\sin(2x)+2(x^2-1)\\cos(2x)' },
], { mode: 'derivative', toleranceDp: 2 });
