import { BaseLevel } from './BaseLevel.js';

export default new BaseLevel('trigDiffRulesHard', 'Trigonometric with Rules — Hard', [
  { problem: '\\frac{d}{dx}(\\sin(3x)\\cos(5x))', answer: '3\\cos(3x)\\cos(5x)-5\\sin(3x)\\sin(5x)' },
  { problem: '\\frac{d}{dx}(\\sin(2x)\\sin(4x))', answer: '2\\cos(2x)\\sin(4x)+4\\sin(2x)\\cos(4x)' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\sin(2x)}{x}\\right)', answer: '\\frac{2x\\cos(2x)-\\sin(2x)}{x^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{1}{1+\\sin x}\\right)', answer: '-\\frac{\\cos x}{(1+\\sin x)^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\sin x}{1+\\cos x}\\right)', answer: '\\frac{1}{1+\\cos x}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{1-\\sin x}{\\cos x}\\right)', answer: '-\\frac{1}{1+\\sin x}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\cos x}{\\cos x+\\sin x}\\right)', answer: '-\\frac{1}{(\\cos x+\\sin x)^2}' },
  { problem: '\\frac{d}{dx}(\\sin 2x\\tan 3x)', answer: '3\\sin 2x\\sec^2 3x+2\\tan 3x\\cos 2x' },
  { problem: '\\frac{d}{dx}\\left(\\frac{3x+4}{\\sin 5x}\\right)', answer: '\\frac{3\\sin 5x-5(3x+4)\\cos 5x}{\\sin^2 5x}' },
  { problem: '\\frac{d}{dx}(\\cos(2x)\\cos(4x))', answer: '-2\\sin(2x)\\cos(4x)-4\\cos(2x)\\sin(4x)' },
  { problem: '\\frac{d}{dx}(\\sin x\\cos(3x))', answer: '\\cos x\\cos(3x)-3\\sin x\\sin(3x)' },
  { problem: '\\frac{d}{dx}(\\sin(4x)\\cos x)', answer: '4\\cos(4x)\\cos x-\\sin(4x)\\sin x' },
  { problem: '\\frac{d}{dx}(\\tan(2x)\\sec(3x))', answer: '\\sec(3x)(2\\sec^2(2x)+3\\tan(2x)\\tan(3x))' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\sin(2x)}{\\cos(3x)}\\right)', answer: '\\frac{2\\cos(2x)\\cos(3x)+3\\sin(2x)\\sin(3x)}{\\cos^2(3x)}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\cos(3x)}{\\sin(2x)}\\right)', answer: '-\\frac{3\\sin(3x)\\sin(2x)+2\\cos(3x)\\cos(2x)}{\\sin^2(2x)}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{1}{1+\\cos x}\\right)', answer: '\\frac{\\sin x}{(1+\\cos x)^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{1}{\\sin x+\\cos x}\\right)', answer: '\\frac{\\sin x-\\cos x}{(\\sin x+\\cos x)^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\sin x}{\\sin x-\\cos x}\\right)', answer: '-\\frac{1}{(\\sin x-\\cos x)^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\cos x}{1-\\sin x}\\right)', answer: '\\frac{1}{1-\\sin x}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{1+\\sin x}{1-\\sin x}\\right)', answer: '\\frac{2\\cos x}{(1-\\sin x)^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{2x+1}{\\cos(2x)}\\right)', answer: '\\frac{2\\cos(2x)+2(2x+1)\\sin(2x)}{\\cos^2(2x)}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x^2}{\\sin(3x)}\\right)', answer: '\\frac{2x\\sin(3x)-3x^2\\cos(3x)}{\\sin^2(3x)}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x+1}{\\tan(2x)}\\right)', answer: '\\frac{\\tan(2x)-2(x+1)\\sec^2(2x)}{\\tan^2(2x)}' },
  { problem: '\\frac{d}{dx}(x\\sin(x^2))', answer: '\\sin(x^2)+2x^2\\cos(x^2)' },
  { problem: '\\frac{d}{dx}(x\\cos(x^2))', answer: '\\cos(x^2)-2x^2\\sin(x^2)' },
  { problem: '\\frac{d}{dx}(x^2\\sin(x^2))', answer: '2x(\\sin(x^2)+x^2\\cos(x^2))' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\sin(3x)}{\\cos(2x)}\\right)', answer: '\\frac{3\\cos(3x)\\cos(2x)+2\\sin(3x)\\sin(2x)}{\\cos^2(2x)}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\sin x+\\cos x}{\\sin x-\\cos x}\\right)', answer: '-\\frac{2}{(\\sin x-\\cos x)^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\tan x}{1+\\tan x}\\right)', answer: '\\frac{\\sec^2 x}{(1+\\tan x)^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x}{\\cos^2 x}\\right)', answer: '\\sec^2 x(1+2x\\tan x)' },
], { mode: 'derivative', toleranceDp: 2 });
