import { BaseLevel } from './BaseLevel.js';

export default new BaseLevel('trigDiffRulesEasy', 'Trigonometric with Rules — Easy', [
  { problem: '\\frac{d}{dx}(\\sec x)', answer: '\\sec x\\tan x' },
  { problem: '\\frac{d}{dx}(\\csc x)', answer: '-\\csc x\\cot x' },
  { problem: '\\frac{d}{dx}(\\cot x)', answer: '-\\csc^2 x' },
  { problem: '\\frac{d}{dx}(2\\sec x)', answer: '2\\sec x\\tan x' },
  { problem: '\\frac{d}{dx}(3\\csc x)', answer: '-3\\csc x\\cot x' },
  { problem: '\\frac{d}{dx}(2\\cot x)', answer: '-2\\csc^2 x' },
  { problem: '\\frac{d}{dx}(x\\sin x)', answer: 'x\\cos x+\\sin x' },
  { problem: '\\frac{d}{dx}(\\sin x\\cos x)', answer: '\\cos^2 x-\\sin^2 x' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\sin x}{x}\\right)', answer: '\\frac{x\\cos x-\\sin x}{x^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\cos x}{x}\\right)', answer: '\\frac{-x\\sin x-\\cos x}{x^2}' },
  { problem: '\\frac{d}{dx}(x\\cos x)', answer: '\\cos x-x\\sin x' },
  { problem: '\\frac{d}{dx}(x\\tan x)', answer: '\\tan x+x\\sec^2 x' },
  { problem: '\\frac{d}{dx}(x\\sec x)', answer: '\\sec x+x\\sec x\\tan x' },
  { problem: '\\frac{d}{dx}(x\\csc x)', answer: '\\csc x-x\\csc x\\cot x' },
  { problem: '\\frac{d}{dx}(x\\cot x)', answer: '\\cot x-x\\csc^2 x' },
  { problem: '\\frac{d}{dx}(x^2\\sin x)', answer: '2x\\sin x+x^2\\cos x' },
  { problem: '\\frac{d}{dx}(x^2\\cos x)', answer: '2x\\cos x-x^2\\sin x' },
  { problem: '\\frac{d}{dx}(x^2\\tan x)', answer: '2x\\tan x+x^2\\sec^2 x' },
  { problem: '\\frac{d}{dx}(x^3\\sin x)', answer: '3x^2\\sin x+x^3\\cos x' },
  { problem: '\\frac{d}{dx}(x^3\\cos x)', answer: '3x^2\\cos x-x^3\\sin x' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\sin x}{x^2}\\right)', answer: '\\frac{x\\cos x-2\\sin x}{x^3}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\cos x}{x^2}\\right)', answer: '-\\frac{x\\sin x+2\\cos x}{x^3}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\tan x}{x}\\right)', answer: '\\frac{x\\sec^2 x-\\tan x}{x^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x}{\\sin x}\\right)', answer: '\\frac{\\sin x-x\\cos x}{\\sin^2 x}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x}{\\cos x}\\right)', answer: '\\frac{\\cos x+x\\sin x}{\\cos^2 x}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{x}{\\tan x}\\right)', answer: '\\frac{\\tan x-x\\sec^2 x}{\\tan^2 x}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\sec x}{x}\\right)', answer: '\\frac{\\sec x(x\\tan x-1)}{x^2}' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\cot x}{x}\\right)', answer: '-\\frac{x\\csc^2 x+\\cot x}{x^2}' },
  { problem: '\\frac{d}{dx}((1+x)\\sin x)', answer: '\\sin x+(1+x)\\cos x' },
  { problem: '\\frac{d}{dx}((x-1)\\cos x)', answer: '\\cos x-(x-1)\\sin x' },
  { problem: '\\frac{d}{dx}((x+2)\\tan x)', answer: '\\tan x+(x+2)\\sec^2 x' },
  { problem: '\\frac{d}{dx}((2x+1)\\sin x)', answer: '2\\sin x+(2x+1)\\cos x' },
  { problem: '\\frac{d}{dx}((x^2+1)\\sin x)', answer: '2x\\sin x+(x^2+1)\\cos x' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\sin^2 x}{x^2}\\right)', answer: '\\frac{x\\sin 2x-2\\sin^2 x}{x^3}' },
  { problem: '\\frac{d}{dx}((x^2-1)\\cos x)', answer: '2x\\cos x-(x^2-1)\\sin x' },
  { problem: '\\frac{d}{dx}\\left(\\frac{\\tan x}{x^2}\\right)', answer: '\\frac{x\\sec^2 x-2\\tan x}{x^3}' },
], { mode: 'derivative', toleranceDp: 2 });
