// levels/addSubtractTermsMedium.js
import { BaseLevel } from './BaseLevel.js';
export default new BaseLevel(
    'addSubtractTermsMedium',
    'Like Terms (Medium)',
    [
            // Four term expressions
            {problem: "3x + 5x - 2x + 4x", answer: "10x"},
            {problem: "8a - 3a + 6a - a", answer: "10a"},
            {problem: "7b + 2b - 4b + 8b", answer: "13b"},
            {problem: "12y - 5y - 3y + 9y", answer: "13y"},
            {problem: "9x + 4x + 7x - 5x", answer: "15x"},
            {problem: "15x - 8x + 3x - 6x", answer: "4x"},
            {problem: "11x - 7x + 12x - 4x", answer: "12x"},
            {problem: "18x + 5x - 9x + 2x", answer: "16x"},
            {problem: "13x - 6x - 2x + 11x", answer: "16x"},
            {problem: "20x + 8x - 12x - 3x", answer: "13x"},

            // Mixed with multiple constants
            {problem: "4x + 7 + 6x - 3", answer: "10x + 4"},
            {problem: "9a - 5 + 2a + 8", answer: "11a + 3"},
            {problem: "7b + 12 - 3b - 4", answer: "4b + 8"},
            {problem: "11y - 8 + 5y + 6", answer: "16y - 2"},
            {problem: "6x + 15 + 9x - 11", answer: "15x + 4"},
            {problem: "13x - 7 - 4x + 12", answer: "9x + 5"},
            {problem: "8x + 9 + 7x - 6", answer: "15x + 3"},
            {problem: "12x - 14 + 4x + 9", answer: "16x - 5"},
            {problem: "10x + 6 - 7x - 2", answer: "3x + 4"},
            {problem: "17x - 13 + 8x - 5", answer: "25x - 18"},

            // Negative coefficients
            {problem: "-3x + 8x", answer: "5x"},
            {problem: "7a - 12a", answer: "-5a"},
            {problem: "-9b - 4b", answer: "-13b"},
            {problem: "-6y + 15y", answer: "9y"},
            {problem: "11x - 18x", answer: "-7x"},
            {problem: "-8x - 7x", answer: "-15x"},
            {problem: "-5x + 13x", answer: "8x"},
            {problem: "9x - 17x", answer: "-8x"},
            {problem: "-12x - 3x", answer: "-15x"},
            {problem: "-4x + 19x", answer: "15x"},

            // Multiple variables (different types)
            {problem: "3x + 5y + 2x", answer: "5x + 5y"},
            {problem: "7a - 4b + 3a", answer: "10a - 4b"},
            {problem: "9x + 2y - 5x", answer: "4x + 2y"},
            {problem: "6x + 8y + 4x", answer: "10x + 8y"},
            {problem: "11x - 7y - 3x", answer: "8x - 7y"},
            {problem: "4x + 9y + 7x", answer: "11x + 9y"},
            {problem: "8x - 6y - 2x", answer: "6x - 6y"},
            {problem: "12x + 5y - 8x", answer: "4x + 5y"},
            {problem: "15a - 9b + 6a", answer: "21a - 9b"},
            {problem: "10x + 7y - 4x", answer: "6x + 7y"},

            // ADD YOUR TEXTBOOK QUESTIONS HERE using the format:
            {problem: "2x - 5x", answer: "-3x"},
            {problem: "-4y + 3y", answer: "-y"},
            {problem: "-2x - 3x", answer: "-5x"},
            {problem: "-4x + 7x", answer: "3x"},
            {problem: "4x - 3x - 2x", answer: "-x"},
            {problem: "x + 3x - 5x", answer: "-x"},
            {problem: "8x - x - 7x", answer: "0"},
            {problem: "3b - 5b + 4b + 9b", answer: "11b"},
            {problem: "-5x + 3x - x - 7x", answer: "-10x"},
            {problem: "6x - 5y - y", answer: "6x - 6y"},
            {problem: "xy + 2y + 3xy", answer: "4xy + 2y"},
            {problem: "-3x + x", answer: "-2x"},
            {problem: "-3x - x", answer: "-4x"},
            {problem: "-2a + 3a + 4a", answer: "5a"},
            {problem: "-2a - 3a + 4a", answer: "-a"},
            {problem: "-2a - 3a - 4a", answer: "-9a"},
            {problem: "-2a + 3a - 4a", answer: "-3a"},
            {problem: "2y - 3y", answer: "-y"},
            {problem: "-3a - 7a", answer: "-10a"},
            {problem: "-8b + 5b", answer: "-3b"},
            {problem: "-2ab - ba", answer: "-3ab"},
            {problem: "-3xy + 7xy", answer: "4xy"},
            {problem: "6a + 4a", answer: "10a"},
            {problem: "8x + 7x", answer: "15x"},
            {problem: "7xy + 5xy - 3y", answer: "12xy - 3y"},
            {problem: "12y - 4y", answer: "8y"},
            {problem: "6ab - 2ab - ba", answer: "3ab"},
            {problem: "6xy + xy + 4y", answer: "7xy + 4y"},
            {problem: "5ab + 3 + 7ba", answer: "12ab + 3"},
            {problem: "2 - 5x - x", answer: "2 - 6x"},
            {problem: "6x + 5 - 2x + 1", answer: "4x + 6"},
            {problem: "5x + 1 + 6x + 3", answer: "11x + 4"},
            {problem: "7a + 12a", answer: "19a"},
            {problem: "15x - 6x", answer: "9x"},
            {problem: "16xy - 3xy", answer: "13xy"},
            {problem: "10ab + 4ab", answer: "14ab"},
            {problem: "11ab - 5ab + ab", answer: "7ab"},
            {problem: "3x + 15x - 2x", answer: "16x"},
            {problem: "15x - 2x - 3x", answer: "10x"},
            {problem: "7x + 2x + 8 + 4", answer: "9x + 12"},
            {problem: "10 + 5x + 2 + 7x", answer: "12x + 12"},
            {problem: "11a + 4 - 2a + 12a", answer: "21a + 4"},
            {problem: "12xy - 3yx + 5xy - yx", answer: "13xy"},
            {problem: "-4x^2 + 3x^2", answer: "-x^2"},
            {problem: "7x + 4 - 2x + 8", answer: "5x + 12"},
            {problem: "4a - 4 + 5b + b", answer: "4a + 6b - 4"},
            {problem: "10a + 3 + 4b - 2a", answer: "8a + 4b + 3"},
            {problem: "4 + 10x - 3x", answer: "4 + 7x"},
            {problem: "11a + 4 - 3a + 9", answer: "8a + 13"},
            {problem: "7ab + 32 - ab + 4", answer: "6ab + 36"},

            // Two-variable expressions — moved from Hard
            {problem: "8a + b - 4b - 7a", answer: "a - 3b"},
            {problem: "4a + 5b - a + 2b", answer: "3a + 7b"},
            {problem: "2a + 4b + 3a + 5b", answer: "5a + 9b"},
            {problem: "4x + 3y + 2x + 2y", answer: "6x + 5y"},
            {problem: "10x + 3x + 5y + 3y", answer: "13x + 8y"},
            {problem: "2a + 5a + 13b - 2b", answer: "7a + 11b"},
            {problem: "10a + 5b + 3a + 4b", answer: "13a + 9b"},
            {problem: "2a + a + 4b + b", answer: "3a + 5b"},
            {problem: "5a + 2a + b + 8b", answer: "7a + 9b"},
            {problem: "3x - 2x + 2y + 4y", answer: "x + 6y"},
            {problem: "3x + 7x + 3y - 4x + y", answer: "6x + 4y"},
            {problem: "10 + 7y + 5x + 5x + 2y", answer: "10x + 9y + 10"},
            {problem: "3b + 4b + x + 5b - x", answer: "12b"},
            {problem: "6x + 2y + 3x - 5y", answer: "9x - 3y"}
        ]
);
