// levels/addSubtractTermsEasy.js
import { BaseLevel } from './BaseLevel.js';
export default new BaseLevel(
    'addSubtractTermsEasy',
    'Like Terms (Easy)',
    [

            // Basic Linear Terms
            {problem: "2x + 3x", answer: "5x"},
            {problem: "5a - 2a", answer: "3a"},
            {problem: "4b + b", answer: "5b"},
            {problem: "3y - y", answer: "2y"},
            {problem: "2x + 4x", answer: "6x"},
            {problem: "7x - 3x", answer: "4x"},
            {problem: "x + 2x", answer: "3x"},
            {problem: "6x - 4x", answer: "2x"},
            {problem: "3x + 2x", answer: "5x"},
            {problem: "8x - 5x", answer: "3x"},
            {problem: "4x + 3x", answer: "7x"},
            {problem: "9x - 6x", answer: "3x"},
            {problem: "2x + x", answer: "3x"},
            {problem: "5x - 2x", answer: "3x"},
            {problem: "3x + 4x", answer: "7x"},
            
            // Basic Quadratic Terms
            {problem: "2x^2 + 3x^2", answer: "5x^2"},
            {problem: "4a^2 - a^2", answer: "3a^2"},
            {problem: "3b^2 + 2b^2", answer: "5b^2"},
            {problem: "5y^2 - 3y^2", answer: "2y^2"},
            {problem: "x^2 + 4x^2", answer: "5x^2"},
            {problem: "6x^2 - 2x^2", answer: "4x^2"},
            {problem: "3x^2 + x^2", answer: "4x^2"},
            {problem: "7x^2 - 4x^2", answer: "3x^2"},
            {problem: "8x^2 - 5x^2", answer: "3x^2"},
                        
            // Simple Mixed (variables + constants)
            {problem: "2x + 3", answer: "2x + 3"},
            {problem: "5a - 2 + a", answer: "6a - 2"},
            {problem: "3b + 4 + 2b", answer: "5b + 4"},
            {problem: "x + 5 - 2x", answer: "-x + 5"},
            {problem: "4y + 1 + y", answer: "5y + 1"},
            {problem: "3x - 3 + 2x", answer: "5x - 3"},
            {problem: "2x + 6 - x", answer: "x + 6"},
            {problem: "5x - 1 - 3x", answer: "2x - 1"},
            {problem: "x + 4 + 3x", answer: "4x + 4"},
            {problem: "7x - 5 - 2x", answer: "5x - 5"},
            
            // Three term combinations
            {problem: "2x + 3x + x", answer: "6x"},
            {problem: "5a - 2a + 4a", answer: "7a"},
            {problem: "3b + b - 2b", answer: "2b"},
            {problem: "4y - y + 2y", answer: "5y"},
            {problem: "x + 3x - x", answer: "3x"},
            {problem: "6x - 3x + x", answer: "4x"},
            {problem: "2x + 4x - 3x", answer: "3x"},
            {problem: "7x - 2x - 3x", answer: "2x"},
            {problem: "3x + 2x + 4x", answer: "9x"},
            {problem: "8x - 4x - 2x", answer: "2x"},
            
            // ADD YOUR TEXTBOOK QUESTIONS HERE using the format:
            {problem: "9a - 6a", answer: "3a"},
            {problem: "5x - 4x", answer: "x"},
            {problem: "4b - b", answer: "3b"},
            {problem: "2a - 2a", answer: "0"},
            {problem: "3x + 4x + 2x", answer: "9x"},
            {problem: "8x - x + 3x", answer: "10x"},
            {problem: "3x + x", answer: "4x"},
            {problem: "3x - x", answer: "2x"},
            {problem: "-x + x", answer: "0"},
            {problem: "5y - 5y", answer: "0"},
            {problem: "2xy + 3xy", answer: "5xy"},
            {problem: "9ab - 5ab", answer: "4ab"},
            {problem: "x + 3x + 2x", answer: "6x"},
            {problem: "4xy + 5 - 2xy", answer: "2xy + 5"},
            {problem: "3a + 7a", answer: "10a"},
            {problem: "5x + 2x + 4x", answer: "11x"},
            {problem: "7xy + 2xy - 2xy", answer: "7xy"},
            {problem: "4y - 3y + 8", answer: "y + 8"},
            {problem: "7x + 5 - 4x", answer: "3x + 5"},
            {problem: "4 - 2x + x", answer: "4 - x"},
            {problem: "4xy + 3xy", answer: "7xy"},
            {problem: "4a + 2 + 3a", answer: "7a + 2"},
            {problem: "7 + 2b + 5b", answer: "7 + 7b"},
            {problem: "3x - 2 + 3x", answer: "6x - 2"},
            {problem: "7ab + 4 + 2ab", answer: "9ab + 4"},

            // Larger coefficient linear — moved from Medium
            {problem: "7x + 8x", answer: "15x"},
            {problem: "12a - 5a", answer: "7a"},
            {problem: "9b + 6b", answer: "15b"},
            {problem: "15y - 8y", answer: "7y"},
            {problem: "11x + 4x", answer: "15x"},
            {problem: "18x - 9x", answer: "9x"},
            {problem: "13x - 7x", answer: "6x"},
            {problem: "20x - 12x", answer: "8x"},
            {problem: "14x + 9x", answer: "23x"},
            {problem: "25x - 16x", answer: "9x"},

            // Larger coefficient quadratic — moved from Medium
            {problem: "8x^2 + 7x^2", answer: "15x^2"},
            {problem: "12a^2 - 5a^2", answer: "7a^2"},
            {problem: "15b^2 + 9b^2", answer: "24b^2"},
            {problem: "18y^2 - 11y^2", answer: "7y^2"},
            {problem: "10x^2 + 13x^2", answer: "23x^2"},
            {problem: "22x^2 - 14x^2", answer: "8x^2"},
            {problem: "16x^2 + 7x^2", answer: "23x^2"},
            {problem: "25x^2 - 18x^2", answer: "7x^2"},
            {problem: "19x^2 + 12x^2", answer: "31x^2"},
            {problem: "30x^2 - 17x^2", answer: "13x^2"},

            // Variable + constant (3-term) — moved from Medium
            {problem: "5x + 8 - 2x", answer: "3x + 8"},
            {problem: "12a - 7 + 3a", answer: "15a - 7"},
            {problem: "9b + 15 - 4b", answer: "5b + 15"},
            {problem: "7y - 12 + 8y", answer: "15y - 12"},
            {problem: "11x + 6 - 7x", answer: "4x + 6"},
            {problem: "18x - 9 - 5x", answer: "13x - 9"},
            {problem: "14x + 11 + 3x", answer: "17x + 11"},
            {problem: "20x - 15 - 8x", answer: "12x - 15"},
            {problem: "16x + 7 + 9x", answer: "25x + 7"},
            {problem: "22x - 18 - 6x", answer: "16x - 18"}
        ]
);
