// levels/expandAndSimplifyMedium.js
import { BaseLevel } from './BaseLevel.js';
export default new BaseLevel(
    'expandAndSimplifyMedium',
    'Expanding & Simplifying (Medium)',
    [
            // Single bracket with negative outer factor
            {problem: "5 - (x - 6)", answer: "11 - x"},
            {problem: "9 - (x - 3)", answer: "12 - x"},
            {problem: "5 - (3 + 2x)", answer: "2 - 2x"},
            {problem: "4 - (3x - 2)", answer: "6 - 3x"},
            {problem: "3 - (x + 1)", answer: "2 - x"},
            {problem: "-3(a + 2) + 10", answer: "-3a + 4"},
            {problem: "3 - 4(x - 2)", answer: "11 - 4x"},
            {problem: "1 - 5(x + 4)", answer: "-5x - 19"},
            {problem: "2 - 3(x + 2)", answer: "-3x - 4"},
            {problem: "8 - 2(x - 3)", answer: "14 - 2x"},
            {problem: "10 - 2(y + 3)", answer: "4 - 2y"},
            {problem: "9 - 4(x - 1)", answer: "13 - 4x"},
            {problem: "12 - (x + 5)", answer: "7 - x"},
            {problem: "6 - (2 - 3x)", answer: "3x + 4"},
            {problem: "4y - 2(y - 3) + 1", answer: "2y + 7"},
            {problem: "8 - 2(3x + 1) + x", answer: "6 - 5x"},
            {problem: "7x - 4(x - 2) - 3", answer: "3x + 5"},

            // Single bracket negative outer, complex sign-flip patterns
            {problem: "-3(x - 4) + 1", answer: "13 - 3x"},
            {problem: "-3(x - 4) - 2", answer: "10 - 3x"},
            {problem: "-3(x - 4) - x", answer: "12 - 4x"},
            {problem: "-3(x - 4) - 3x", answer: "12 - 6x"},
            {problem: "2 - 3(x - 4)", answer: "14 - 3x"},
            {problem: "-3 - 3(x - 4)", answer: "9 - 3x"},
            {problem: "x - 3(x - 4)", answer: "12 - 2x"},
            {problem: "-2x - 3(x - 4)", answer: "12 - 5x"},
            {problem: "-3(2x + 1) + (2x - 3)", answer: "-4x - 6"},
            {problem: "-2(x + 2) + 3(x - 1)", answer: "x - 7"},
            {problem: "-2(3x - 4) + 5(x + 1)", answer: "-x + 13"},

            // Two brackets, both with positive outer factors
            {problem: "3(3 + 5x) + 4(10x + 7)", answer: "55x + 37"},
            {problem: "2(9 + 10x) + 4(3x + 3)", answer: "32x + 30"},
            {problem: "2(9 + 6x) + 7(2 + 9x)", answer: "75x + 32"},
            {problem: "6(10 - 6x) + 4(10x - 5)", answer: "4x + 40"},
            {problem: "2(x + 3) + 3(x + 2)", answer: "5x + 12"},
            {problem: "2(x - 3) + 2(x - 1)", answer: "4x - 8"},
            {problem: "3(2x + 1) + 5(x - 1)", answer: "11x - 2"},
            {problem: "4(3x + 2) + 5(x - 3)", answer: "17x - 7"},
            {problem: "2(x + 4) + 3(x + 5)", answer: "5x + 23"},
            {problem: "4(a + 2) + 6(a + 3)", answer: "10a + 26"},
            {problem: "6(3y + 2) + 3(y - 3)", answer: "21y + 3"},
            {problem: "3(2x + 3) + 3(3x - 1)", answer: "15x + 6"},
            {problem: "3(2 + 5x) + 2(3x + 1)", answer: "21x + 8"},
            {problem: "4(2 + 5x) + 3(4 - 2x)", answer: "14x + 20"},
            {problem: "2(4x - 3) - 2(3x - 1)", answer: "2x - 4"},
            {problem: "3(3x - 1) - 2(2 - x)", answer: "11x - 7"},
            {problem: "3(x - 2) - 2(x - 5)", answer: "x + 4"},
            {problem: "2(2 + 6b) - 3(4b - 2)", answer: "10"},
            {problem: "3(2x + 3) - 5(2 - x)", answer: "11x - 1"},
            {problem: "2(x + 4) + 3(x + 2)", answer: "5x + 14"},
            {problem: "4(3x - 2) - 3(2x - 1)", answer: "6x - 5"},
            {problem: "4(x + 5) - 2(x - 1)", answer: "2x + 22"},
            {problem: "6(2a - 3) + 3(a + 4)", answer: "15a - 6"},
            {problem: "2(3b + 7) - (b - 5)", answer: "5b + 19"},
            {problem: "5(x - 2) + 3(2x + 1)", answer: "11x - 7"},
            {problem: "7(2y + 1) - 4(y - 3)", answer: "10y + 19"},
            {problem: "3(4x - 5) + 2(3x + 7)", answer: "18x - 1"},
            {problem: "2(x + 1) + 4(x + 3)", answer: "6x + 14"},
            {problem: "3(y - 2) + 5(y + 1)", answer: "8y - 1"},
            {problem: "4(2a + 3) + 2(a - 5)", answer: "10a + 2"},
            {problem: "6(b - 1) + 3(2b + 4)", answer: "12b + 6"},
            {problem: "5(3x + 2) - 2(x + 7)", answer: "13x - 4"},
            {problem: "7(y + 4) - 3(2y - 1)", answer: "y + 31"},
        ]
);
