import { BaseLevel } from './BaseLevel.js';

export default new BaseLevel(
    'factoriseWithIndicesEasy',
    'Factorise with Indices (Easy)',
    [
        { problem: "3 \\times 3^x",                           answer: "3^{x+1}" },
        { problem: "32 \\times 2^x",                          answer: "2^{x+5}" },
        { problem: "\\frac{1}{2} \\times 2^x",                answer: "2^{x-1}" },
        { problem: "5^{2x} \\times 5^{3x} \\div 25^x",        answer: "5^{3x}" },
        { problem: "7^{3x+4} \\div 49^{9-3x}",                answer: "7^{9x-14}" },
        { problem: "(9^x)^2 \\times (3^{3x})^3",              answer: "3^{13x}" },
        { problem: "8^{2x} \\div 2^{6x} \\times 4^x",         answer: "2^{2x}" },
        { problem: "9^{3m+1} \\times 3^{4m-1}",               answer: "3^{10m+1}" },
        { problem: "32^n \\div 8^{2n} \\div 4^{3n}",          answer: "2^{-7n}" },
        { problem: "4^x \\times 8^x \\div 2^x",               answer: "2^{4x}" },
        { problem: "27^x \\times 3^{2x}",                     answer: "3^{5x}" },
        { problem: "3^{x+2} \\times 3^{x-1}",                 answer: "3^{2x+1}" },
        { problem: "9^x \\div 3^{3x}",                        answer: "3^{-x}" },
        { problem: "4^{x+1} \\times 2^{2x}",                  answer: "2^{4x+2}" },
        { problem: "(2^x)^3 \\times 4^x",                     answer: "2^{5x}" },
        { problem: "9^{2x} \\div 3^x",                        answer: "3^{3x}" },
        { problem: "2^{3x} \\times 8^x",                      answer: "2^{6x}" },
        { problem: "25^x \\div 5^{3x}",                       answer: "5^{-x}" },
        { problem: "3^x + 3^x + 3^x",                         answer: "3^{x+1}" },
        { problem: "3^8 - 3^7",                               answer: "2 \\times 3^7" },
        { problem: "3^n + 3^{n+1}",                           answer: "4 \\times 3^n" },
        { problem: "5^n - 5^{n-3}",                           answer: "124 \\times 5^{n-3}" },
        { problem: "2^n + 2^n",                               answer: "2^{n+1}" },
        { problem: "2^{n+1} + 2^n",                           answer: "3 \\times 2^n" },
        { problem: "7^n - 7^{n-1}",                           answer: "6 \\times 7^{n-1}" },
        { problem: "5^{n+2} + 5^n",                           answer: "26 \\times 5^n" },
        { problem: "4^n + 4^{n+1}",                           answer: "5 \\times 2^{2n}" },
        { problem: "2^{x+2} - 2^x",                           answer: "3 \\times 2^x" },
        { problem: "3^{n+2} - 3^{n+1}",                       answer: "2 \\times 3^{n+1}" },
        { problem: "2^n + 2^{n-1}",                           answer: "3 \\times 2^{n-1}" },
        { problem: "5^n - 5^{n-1}",                           answer: "4 \\times 5^{n-1}" },
        { problem: "7^{n+1} + 7^{n+2}",                       answer: "8 \\times 7^{n+1}" },
        { problem: "6^6 + 6^6 + 6^6 + 6^6 + 6^6 + 6^6",     answer: "6^7" },
    ]
);
