// levels/simplifySurdsEasy.js
import { BaseLevel } from './BaseLevel.js';
export default new BaseLevel(
    'simplifySurdsEasy',
    'Surd Simplification (Easy)',
    [
            // Perfect-square variable extraction
            {problem: "\\sqrt{x^2}", answer: "x"},
            {problem: "\\sqrt{a^2}", answer: "a"},
            {problem: "\\sqrt{y^2}", answer: "y"},
            {problem: "\\sqrt{4x^2}", answer: "2x"},
            {problem: "\\sqrt{9x^2}", answer: "3x"},
            {problem: "\\sqrt{16a^2}", answer: "4a"},
            {problem: "\\sqrt{25y^2}", answer: "5y"},
            {problem: "\\sqrt{36x^2}", answer: "6x"},
            {problem: "\\sqrt{49a^2}", answer: "7a"},
            {problem: "\\sqrt{x^4}", answer: "x^2"},
            {problem: "\\sqrt{x^6}", answer: "x^3"},
            {problem: "\\sqrt{a^4}", answer: "a^2"},
            {problem: "\\sqrt{16x^4}", answer: "4x^2"},
            {problem: "\\sqrt{x^2y^2}", answer: "xy"},
            {problem: "\\sqrt{a^2b^2}", answer: "ab"},
            {problem: "\\sqrt{4x^2y^2}", answer: "2xy"},
            {problem: "\\sqrt{9a^2b^2}", answer: "3ab"},
            {problem: "\\sqrt{49x^2y^2}", answer: "7xy"},
            {problem: "\\sqrt{x^4y^2}", answer: "x^2y"},
            {problem: "\\sqrt{x^2y^4}", answer: "xy^2"},
            {problem: "\\sqrt{a^6b^2}", answer: "a^3b"},
            // One factor stays under the root
            {problem: "\\sqrt{x^2y}", answer: "x\\sqrt{y}"},
            {problem: "\\sqrt{a^2b}", answer: "a\\sqrt{b}"},
            {problem: "\\sqrt{4x^2y}", answer: "2x\\sqrt{y}"},
            {problem: "\\sqrt{9a^2b}", answer: "3a\\sqrt{b}"},
            {problem: "\\sqrt{25x^2y}", answer: "5x\\sqrt{y}"},
            {problem: "\\sqrt{x^3}", answer: "x\\sqrt{x}"},
            {problem: "\\sqrt{a^3}", answer: "a\\sqrt{a}"},
            {problem: "\\sqrt{x^5}", answer: "x^2\\sqrt{x}"},
            {problem: "\\sqrt{a^2b^3}", answer: "ab\\sqrt{b}"},
            // Squaring single surds
            {problem: "(\\sqrt{x})^2", answer: "x"},
            {problem: "(\\sqrt{a})^2", answer: "a"},
            {problem: "(\\sqrt{2x})^2", answer: "2x"},
            {problem: "(\\sqrt{3a})^2", answer: "3a"},
            {problem: "(\\sqrt{5y})^2", answer: "5y"},
            {problem: "2(\\sqrt{x})^2", answer: "2x"},
            {problem: "3(\\sqrt{a})^2", answer: "3a"},
            {problem: "5(\\sqrt{y})^2", answer: "5y"},
            // A handful of numeric questions for fluency (small radicands)
            {problem: "\\sqrt{4}", answer: "2"},
            {problem: "\\sqrt{9}", answer: "3"},
            {problem: "\\sqrt{16}", answer: "4"},
            {problem: "\\sqrt{8}", answer: "2\\sqrt{2}"},
            {problem: "\\sqrt{12}", answer: "2\\sqrt{3}"},
            {problem: "\\sqrt{18}", answer: "3\\sqrt{2}"},
            {problem: "\\sqrt{20}", answer: "2\\sqrt{5}"},
            {problem: "\\sqrt{27}", answer: "3\\sqrt{3}"},
            {problem: "\\sqrt{50}", answer: "5\\sqrt{2}"},
            {problem: "(\\sqrt{2})^2", answer: "2"},
            {problem: "(\\sqrt{5})^2", answer: "5"},
            {problem: "2(\\sqrt{3})^2", answer: "6"}
        ]
);
