/**
 * Level registry — single source of truth for level metadata across all apps.
 *
 * Loaded as a classic script (must run BEFORE any app's ES module config.js
 * and BEFORE shared/hubLeaderboard.js). Exposes window.LevelRegistry.
 *
 * Each app's config.js consumes window.LevelRegistry[app].LEVEL_GROUPS instead
 * of duplicating the level structure. shared/hubLeaderboard.js derives its
 * HUB_LEVELS from the same source. The algebra dynamic script loader uses
 * the keys here to inject <script src="levels/{key}.js"> tags.
 *
 * Adding a new level: add one entry here and create the level file.
 */
window.LevelRegistry = {
    algebra: {
        appLabel: 'Algebra',
        LEVEL_GROUPS: {
            "Foundational Skills": [
                { key: 'addSubtractTermsEasy', name: 'Add Subtract Terms<br>Easy', value: 'liketerms-easy' },
                { key: 'addSubtractTermsMedium', name: 'Add Subtract Terms<br>Medium', value: 'liketerms-medium' },
                { key: 'addSubtractTermsHard', name: 'Add Subtract Terms<br>Hard', value: 'liketerms-hard' },
                { key: 'multiplyTermsEasy', name: 'Multiply Terms<br>Easy', value: 'multiply-easy' },
                { key: 'multiplyTermsMedium', name: 'Multiply Terms<br>Medium', value: 'multiply-medium' },
                { key: 'multiplyTermsHard', name: 'Multiply Terms<br>Hard', value: 'multiply-hard' },
                { key: 'divideTermsEasy', name: 'Divide Terms<br>Easy', value: 'cancelling-easy' },
                { key: 'divideTermsMedium', name: 'Divide Terms<br>Medium', value: 'cancelling-medium' },
                { key: 'divideTermsHard', name: 'Divide Terms<br>Hard', value: 'cancelling-hard' },
                { key: 'mixedSimplificationEasy', name: 'Mixed Simplification<br>Easy', value: 'mixedalgsimp-easy' },
                { key: 'mixedSimplificationMedium', name: 'Mixed Simplification<br>Medium', value: 'mixedalgsimp-medium' },
                { key: 'mixedSimplificationHard', name: 'Mixed Simplification<br>Hard', value: 'mixedalgsimp-hard' },
                { key: 'expandSingleBracketsEasy', name: 'Expand Single Brackets<br>Easy', value: 'expansion-easy' },
                { key: 'expandSingleBracketsMedium', name: 'Expand Single Brackets<br>Medium', value: 'expansion-medium' },
                { key: 'expandSingleBracketsHard', name: 'Expand Single Brackets<br>Hard', value: 'expansion-hard' },
                { key: 'multiplicationIndexLawEasy', name: 'Multiplication Index Law<br>Easy', value: 'indexlaw-easy' },
                { key: 'multiplicationIndexLawMedium', name: 'Multiplication Index Law<br>Medium', value: 'indexlaw-medium' },
                { key: 'multiplicationIndexLawHard', name: 'Multiplication Index Law<br>Hard', value: 'indexlaw-hard' },
                { key: 'divisionIndexLawEasy', name: 'Division Index Law<br>Easy', value: 'indexlawdivision-easy' },
                { key: 'divisionIndexLawMedium', name: 'Division Index Law<br>Medium', value: 'indexlawdivision-medium' },
                { key: 'divisionIndexLawHard', name: 'Division Index Law<br>Hard', value: 'indexlawdivision-hard' },
                { key: 'powerOfPowerAndZeroPowerEasy', name: 'Power of Power & Zero Power<br>Easy', value: 'indexlawpower-easy' },
                { key: 'powerOfPowerAndZeroPowerMedium', name: 'Power of Power & Zero Power<br>Medium', value: 'indexlawpower-medium' },
                { key: 'powerOfPowerAndZeroPowerHard', name: 'Power of Power & Zero Power<br>Hard', value: 'indexlawpower-hard' },
                { key: 'mixedIndexLawsEasy', name: 'Mixed Index Laws<br>Easy', value: 'mixedindexlaws-easy' },
                { key: 'mixedIndexLawsMedium', name: 'Mixed Index Laws<br>Medium', value: 'mixedindexlaws-medium' },
                { key: 'mixedIndexLawsHard', name: 'Mixed Index Laws<br>Hard', value: 'mixedindexlaws-hard' },
                { key: 'orderOfOperationsEasy', name: 'Order of Operations<br>Easy', value: 'order-operations-easy' },
                { key: 'orderOfOperationsMedium', name: 'Order of Operations<br>Medium', value: 'order-operations-medium' },
                { key: 'orderOfOperationsHard', name: 'Order of Operations<br>Hard', value: 'order-operations-hard' },
                { key: 'factoriseIntoSingleBracketsEasy', name: 'Factorise into Single Brackets<br>Easy', value: 'factorising-easy' },
                { key: 'factoriseIntoSingleBracketsMedium', name: 'Factorise into Single Brackets<br>Medium', value: 'factorising-medium' },
                { key: 'factoriseIntoSingleBracketsHard', name: 'Factorise into Single Brackets<br>Hard', value: 'factorising-hard' },
            ],

            "Intermediate Skills": [
                { key: 'expandAndSimplifyEasy', name: 'Expand & Simplify<br>Easy', value: 'expanding-simplifying-easy' },
                { key: 'expandAndSimplifyMedium', name: 'Expand & Simplify<br>Medium', value: 'expanding-simplifying-medium' },
                { key: 'expandAndSimplifyHard', name: 'Expand & Simplify<br>Hard', value: 'expanding-simplifying-hard' },
                { key: 'expandBinomialProductsEasy', name: 'Expand Binomial Products<br>Easy', value: 'expanding-double-brackets-easy' },
                { key: 'expandBinomialProductsMedium', name: 'Expand Binomial Products<br>Medium', value: 'expanding-double-brackets-medium' },
                { key: 'expandBinomialProductsHard', name: 'Expand Binomial Products<br>Hard', value: 'expanding-double-brackets-hard' },
                { key: 'powerOfProductsAndQuotientsEasy', name: 'Power of Products and Quotients<br>Easy', value: 'power-product-quotient-easy' },
                { key: 'powerOfProductsAndQuotientsMedium', name: 'Power of Products and Quotients<br>Medium', value: 'power-product-quotient-medium' },
                { key: 'powerOfProductsAndQuotientsHard', name: 'Power of Products and Quotients<br>Hard', value: 'power-product-quotient-hard' },
                { key: 'addSubtractAlgebraicFractionsEasy', name: 'Add Subtract Algebraic Fractions<br>Easy', value: 'add-subtract-algebraic-fractions-easy' },
                { key: 'addSubtractAlgebraicFractionsMedium', name: 'Add Subtract Algebraic Fractions<br>Medium', value: 'add-subtract-algebraic-fractions-medium' },
                { key: 'addSubtractAlgebraicFractionsHard', name: 'Add Subtract Algebraic Fractions<br>Hard', value: 'add-subtract-algebraic-fractions-hard' },
                { key: 'multiplyDivideAlgebraicFractionsEasy', name: 'Multiply Divide Algebraic Fractions<br>Easy', value: 'multiply-divide-algebraic-fractions-easy' },
                { key: 'multiplyDivideAlgebraicFractionsMedium', name: 'Multiply Divide Algebraic Fractions<br>Medium', value: 'multiply-divide-algebraic-fractions-medium' },
                { key: 'multiplyDivideAlgebraicFractionsHard', name: 'Multiply Divide Algebraic Fractions<br>Hard', value: 'multiply-divide-algebraic-fractions-hard' },
                { key: 'negativeIndicesEasy', name: 'Negative Indices<br>Easy', value: 'negative-indices-easy' },
                { key: 'negativeIndicesMedium', name: 'Negative Indices<br>Medium', value: 'negative-indices-medium' },
                { key: 'negativeIndicesHard', name: 'Negative Indices<br>Hard', value: 'negative-indices-hard' },
                { key: 'factoriseMonicQuadraticTrinomialsEasy', name: 'Factorise Monic Quadratic Trinomials<br>Easy', value: 'factorising-monic-quadratic-trinomials-easy' },
                { key: 'factoriseMonicQuadraticTrinomialsMedium', name: 'Factorise Monic Quadratic Trinomials<br>Medium', value: 'factorising-monic-quadratic-trinomials-medium' },
                { key: 'factoriseMonicQuadraticTrinomialsHard', name: 'Factorise Monic Quadratic Trinomials<br>Hard', value: 'factorising-monic-quadratic-trinomials-hard' },
            ],

            "Advanced Skills": [
                { key: 'addSubtractFractionsWithBinomialNumeratorEasy', name: 'Add Subtract Fractions with Binomial Numerator<br>Easy', value: 'add-subtract-fractions-binomial-easy' },
                { key: 'addSubtractFractionsWithBinomialNumeratorMedium', name: 'Add Subtract Fractions with Binomial Numerator<br>Medium', value: 'add-subtract-fractions-binomial-medium' },
                { key: 'addSubtractFractionsWithBinomialNumeratorHard', name: 'Add Subtract Fractions with Binomial Numerator<br>Hard', value: 'add-subtract-fractions-binomial-hard' },
                { key: 'expandPerfectSquaresEasy', name: 'Expand Perfect Squares<br>Easy', value: 'expanding-perfect-squares-easy' },
                { key: 'expandPerfectSquaresMedium', name: 'Expand Perfect Squares<br>Medium', value: 'expanding-perfect-squares-medium' },
                { key: 'expandPerfectSquaresHard', name: 'Expand Perfect Squares<br>Hard', value: 'expanding-perfect-squares-hard' },
                { key: 'expandDifferenceOfTwoSquaresEasy', name: 'Expand Difference of Two Squares<br>Easy', value: 'expanding-difference-of-two-squares-easy' },
                { key: 'expandDifferenceOfTwoSquaresMedium', name: 'Expand Difference of Two Squares<br>Medium', value: 'expanding-difference-of-two-squares-medium' },
                { key: 'expandDifferenceOfTwoSquaresHard', name: 'Expand Difference of Two Squares<br>Hard', value: 'expanding-difference-of-two-squares-hard' },
                { key: 'mixedExpansionEasy', name: 'Mixed Expansion<br>Easy', value: 'mixed-expansion-easy' },
                { key: 'mixedExpansionMedium', name: 'Mixed Expansion<br>Medium', value: 'mixed-expansion-medium' },
                { key: 'mixedExpansionHard', name: 'Mixed Expansion<br>Hard', value: 'mixed-expansion-hard' },
                { key: 'factorisePerfectSquaresEasy', name: 'Factorise Perfect Squares<br>Easy', value: 'perfect-square-factorisation-easy' },
                { key: 'factorisePerfectSquaresMedium', name: 'Factorise Perfect Squares<br>Medium', value: 'perfect-square-factorisation-medium' },
                { key: 'factorisePerfectSquaresHard', name: 'Factorise Perfect Squares<br>Hard', value: 'perfect-square-factorisation-hard' },
                { key: 'factoriseDifferenceOfTwoSquaresEasy', name: 'Factorise Difference of Two Squares<br>Easy', value: 'difference-of-two-squares-easy' },
                { key: 'factoriseDifferenceOfTwoSquaresMedium', name: 'Factorise Difference of Two Squares<br>Medium', value: 'difference-of-two-squares-medium' },
                { key: 'factoriseDifferenceOfTwoSquaresHard', name: 'Factorise Difference of Two Squares<br>Hard', value: 'difference-of-two-squares-hard' },
                { key: 'noticeBinomialFactorsEasy', name: 'Notice Binomial Factors<br>Easy', value: 'binomial-factors-easy' },
                { key: 'noticeBinomialFactorsMedium', name: 'Notice Binomial Factors<br>Medium', value: 'binomial-factors-medium' },
                { key: 'noticeBinomialFactorsHard', name: 'Notice Binomial Factors<br>Hard', value: 'binomial-factors-hard' },
                { key: 'groupInPairsEasy', name: 'Group in Pairs<br>Easy', value: 'grouping-pairs-easy' },
                { key: 'groupInPairsMedium', name: 'Group in Pairs<br>Medium', value: 'grouping-pairs-medium' },
                { key: 'groupInPairsHard', name: 'Group in Pairs<br>Hard', value: 'grouping-pairs-hard' },
                { key: 'factoriseNonMonicQuadraticTrinomialsEasy', name: 'Factorise Non-monic Quadratic Trinomials<br>Easy', value: 'factorising-non-monic-quadratic-trinomials-easy' },
                { key: 'factoriseNonMonicQuadraticTrinomialsMedium', name: 'Factorise Non-monic Quadratic Trinomials<br>Medium', value: 'factorising-non-monic-quadratic-trinomials-medium' },
                { key: 'factoriseNonMonicQuadraticTrinomialsHard', name: 'Factorise Non-monic Quadratic Trinomials<br>Hard', value: 'factorising-non-monic-quadratic-trinomials-hard' },
                { key: 'mixedFactorisationEasy', name: 'Mixed Factorisation<br>Easy', value: 'mixed-factorisation-easy' },
                { key: 'mixedFactorisationMedium', name: 'Mixed Factorisation<br>Medium', value: 'mixed-factorisation-medium' },
                { key: 'mixedFactorisationHard', name: 'Mixed Factorisation<br>Hard', value: 'mixed-factorisation-hard' },
                { key: 'finishFactorisingEasy', name: 'Finish Factorising<br>Easy', value: 'finish-factorising-easy' },
                { key: 'finishFactorisingMedium', name: 'Finish Factorising<br>Medium', value: 'finish-factorising-medium' },
                { key: 'finishFactorisingHard', name: 'Finish Factorising<br>Hard', value: 'finish-factorising-hard' },
                { key: 'simplifyAlgebraicFractionsByFactorisingEasy', name: 'Simplify Algebraic Fractions by Factorising<br>Easy', value: 'simplify-algebraic-fractions-easy' },
                { key: 'simplifyAlgebraicFractionsByFactorisingMedium', name: 'Simplify Algebraic Fractions by Factorising<br>Medium', value: 'simplify-algebraic-fractions-medium' },
                { key: 'simplifyAlgebraicFractionsByFactorisingHard', name: 'Simplify Algebraic Fractions by Factorising<br>Hard', value: 'simplify-algebraic-fractions-hard' },
                { key: 'multiplyDivideAlgebraicFractionsByFactorisingEasy', name: 'Multiply Divide Algebraic Fractions by Factorising<br>Easy', value: 'multiply-divide-algebraic-fractions-by-factorising-easy' },
                { key: 'multiplyDivideAlgebraicFractionsByFactorisingMedium', name: 'Multiply Divide Algebraic Fractions by Factorising<br>Medium', value: 'multiply-divide-algebraic-fractions-by-factorising-medium' },
                { key: 'multiplyDivideAlgebraicFractionsByFactorisingHard', name: 'Multiply Divide Algebraic Fractions by Factorising<br>Hard', value: 'multiply-divide-algebraic-fractions-by-factorising-hard' },
                { key: 'addSubtractFractionsByFactorisingDenominatorEasy', name: 'Add Subtract Fractions by Factorising Denominator<br>Easy', value: 'add-subtract-fractions-factorising-easy' },
                { key: 'addSubtractFractionsByFactorisingDenominatorMedium', name: 'Add Subtract Fractions by Factorising Denominator<br>Medium', value: 'add-subtract-fractions-factorising-medium' },
                { key: 'addSubtractFractionsByFactorisingDenominatorHard', name: 'Add Subtract Fractions by Factorising Denominator<br>Hard', value: 'add-subtract-fractions-factorising-hard' },
                { key: 'compoundFractionsEasy', name: 'Compound Fractions<br>Easy', value: 'compound-fractions-easy' },
                { key: 'compoundFractionsMedium', name: 'Compound Fractions<br>Medium', value: 'compound-fractions-medium' },
                { key: 'compoundFractionsHard', name: 'Compound Fractions<br>Hard', value: 'compound-fractions-hard' },
                { key: 'simplifySurdsEasy', name: 'Simplify Surds<br>Easy', value: 'surd-simplification-easy' },
                { key: 'simplifySurdsMedium', name: 'Simplify Surds<br>Medium', value: 'surd-simplification-medium' },
                { key: 'simplifySurdsHard', name: 'Simplify Surds<br>Hard', value: 'surd-simplification-hard' },
                { key: 'addSubtractSurdsEasy', name: 'Add Subtract Surds<br>Easy', value: 'adding-subtracting-surds-easy' },
                { key: 'addSubtractSurdsMedium', name: 'Add Subtract Surds<br>Medium', value: 'adding-subtracting-surds-medium' },
                { key: 'addSubtractSurdsHard', name: 'Add Subtract Surds<br>Hard', value: 'adding-subtracting-surds-hard' },
                { key: 'multiplyDivideSurdsEasy', name: 'Multiply Divide Surds<br>Easy', value: 'multiplying-dividing-surds-easy' },
                { key: 'multiplyDivideSurdsMedium', name: 'Multiply Divide Surds<br>Medium', value: 'multiplying-dividing-surds-medium' },
                { key: 'multiplyDivideSurdsHard', name: 'Multiply Divide Surds<br>Hard', value: 'multiplying-dividing-surds-hard' },
                { key: 'expandBracketsWithSurdsEasy', name: 'Expand Brackets with Surds<br>Easy', value: 'expanding-surds-easy' },
                { key: 'expandBracketsWithSurdsMedium', name: 'Expand Brackets with Surds<br>Medium', value: 'expanding-surds-medium' },
                { key: 'expandBracketsWithSurdsHard', name: 'Expand Brackets with Surds<br>Hard', value: 'expanding-surds-hard' },
                { key: 'rationaliseTheDenominatorEasy', name: 'Rationalise the Denominator<br>Easy', value: 'rationalising-denominator-easy' },
                { key: 'rationaliseTheDenominatorMedium', name: 'Rationalise the Denominator<br>Medium', value: 'rationalising-denominator-medium' },
                { key: 'rationaliseTheDenominatorHard', name: 'Rationalise the Denominator<br>Hard', value: 'rationalising-denominator-hard' },
                { key: 'rationaliseBinomialDenominatorEasy', name: 'Rationalise Binomial Denominator<br>Easy', value: 'further-rationalising-denominator-easy' },
                { key: 'rationaliseBinomialDenominatorMedium', name: 'Rationalise Binomial Denominator<br>Medium', value: 'further-rationalising-denominator-medium' },
                { key: 'rationaliseBinomialDenominatorHard', name: 'Rationalise Binomial Denominator<br>Hard', value: 'further-rationalising-denominator-hard' },
                { key: 'evaluateFractionalIndicesEasy', name: 'Evaluate Fractional Indices<br>Easy', value: 'evaluating-fractional-indices-easy' },
                { key: 'evaluateFractionalIndicesMedium', name: 'Evaluate Fractional Indices<br>Medium', value: 'evaluating-fractional-indices-medium' },
                { key: 'evaluateFractionalIndicesHard', name: 'Evaluate Fractional Indices<br>Hard', value: 'evaluating-fractional-indices-hard' },
                { key: 'surdFormToIndexFormEasy', name: 'Surd Form to Index Form<br>Easy', value: 'surd-to-index-easy' },
                { key: 'surdFormToIndexFormMedium', name: 'Surd Form to Index Form<br>Medium', value: 'surd-to-index-medium' },
                { key: 'surdFormToIndexFormHard', name: 'Surd Form to Index Form<br>Hard', value: 'surd-to-index-hard' },
                { key: 'indexFormToSurdFormEasy', name: 'Index Form to Surd Form<br>Easy', value: 'index-form-to-surd-form-easy' },
                { key: 'indexFormToSurdFormMedium', name: 'Index Form to Surd Form<br>Medium', value: 'index-form-to-surd-form-medium' },
                { key: 'indexFormToSurdFormHard', name: 'Index Form to Surd Form<br>Hard', value: 'index-form-to-surd-form-hard' },
                { key: 'completeTheSquareEasy', name: 'Complete the Square<br>Easy', value: 'complete-the-square-easy' },
                { key: 'completeTheSquareMedium', name: 'Complete the Square<br>Medium', value: 'complete-the-square-medium' },
                { key: 'completeTheSquareHard', name: 'Complete the Square<br>Hard', value: 'complete-the-square-hard' },
                { key: 'factoriseWithIndicesEasy', name: 'Factorise with Indices<br>Easy', value: 'factorise-with-indices-easy' },
                { key: 'factoriseWithIndicesMedium', name: 'Factorise with Indices<br>Medium', value: 'factorise-with-indices-medium' },
                { key: 'factoriseWithIndicesHard', name: 'Factorise with Indices<br>Hard', value: 'factorise-with-indices-hard' },
                { key: 'splittingTheNumeratorEasy',   name: 'Splitting the Numerator<br>Easy', value: 'splitting-the-numerator-easy'   },
                { key: 'splittingTheNumeratorMedium', name: 'Splitting the Numerator<br>Medium', value: 'splitting-the-numerator-medium' },
                { key: 'splittingTheNumeratorHard',   name: 'Splitting the Numerator<br>Hard', value: 'splitting-the-numerator-hard'   },
            ]
        }
    },

    mathsfacts: {
        appLabel: 'Number',
        LEVEL_GROUPS: {
            "Number Bonds": [
                { key: 'bonds10', name: 'Bonds to 10', value: 10 },
                { key: 'bonds20', name: 'Bonds to 20', value: 20 },
                { key: 'mixed10-20', name: 'Mixed Bonds 10-20', customMixedRange: [10, 20] },
                { key: 'bonds100', name: 'Bonds to 100', value: 100 },
                { key: 'bonds-10', name: 'Bonds to -10', value: -10 },
                { key: 'bonds-20', name: 'Bonds to -20', value: -20 },
                { key: 'negAddSub', name: 'Add & Subtract Negatives' },
            ],
            "Multiplication & Division": [
                { key: 'group245', name: '× 2 4 5 10' },
                { key: 'group369', name: '× 3 6 9' },
                { key: 'multall', name: '× 2 to 12' },
                { key: 'mixed-negative-mult', name: '× Negatives' },
                { key: 'integerOperations', name: 'Integer Operations' },
                { key: 'multiplyDivideBy100', name: '×÷ 100' },
                { key: 'powersOf10', name: '×÷ Powers of 10' },
                { key: 'double100', name: 'Doubling' },
                { key: 'squares', name: 'Perfect Squares' },
                { key: 'unitConversions', name: 'Unit Conversions' },
            ],
            "Fractions Decimals Percentages": [
                { key: 'hcf', name: 'HCF' },
                { key: 'lcm', name: 'LCM' },
                { key: 'equivFractions', name: 'Equivalent Fractions' },
                { key: 'simplifyFractions', name: 'Simplifying Fractions' },
                { key: 'fdpConversions', name: 'Common FDP Equivalences' },
                { key: 'fdpConversionsMultiples', name: 'FDP Conversions' },
                { key: 'roundingDecimals', name: 'Rounding Decimals' },
                { key: 'fractionOfQuantity', name: 'Fraction of a Quantity' },
                { key: 'percentageOfQuantity', name: 'Percentage of a Quantity' },
                { key: 'increaseDecreasePercentage', name: 'Increase Decrease by Percentage' },
            ]
        }
    },

    trigfacts: {
        appLabel: 'Trigonometry',
        LEVEL_GROUPS: {
            "Unit Circle in Degrees": [
                { key: 'exact_deg_mixed', name: 'Exact Values', type: 'exact', unit: 'deg' },
                { key: 'reference_angles', name: 'Reference Angles', type: 'reference_angles' },
                { key: 'equiv_deg', name: 'Equivalent Ratios', type: 'equivalent', unit: 'deg' },
                { key: 'quad_deg', name: 'Exact Values in all Quadrants', type: 'quadrant', unit: 'deg' },
            ],
            "Degree and Radian Conversion": [
                { key: 'simplify_fractions', name: 'Simplify Fractions<br>over 180', type: 'simplify_fractions' },
                { key: 'deg_to_rad', name: 'Degrees to Radians', type: 'conversion', direction: 'd2r' },
                { key: 'rad_to_deg', name: 'Radians to Degrees', type: 'conversion', direction: 'r2d' },
                { key: 'conv_mixed', name: 'Mixed Conversion', type: 'conversion', direction: 'mixed' },
            ],
            "Working in Radians": [
                { key: 'exact_rad_mixed', name: 'Exact Values', type: 'exact', unit: 'rad' },
                { key: 'reference_angles_rad', name: 'Reference Angles', type: 'reference_angles_rad' },
                { key: 'equiv_rad', name: 'Equivalent Ratios', type: 'equivalent', unit: 'rad' },
                { key: 'quad_rad', name: 'Exact Values in all Quadrants', type: 'quadrant', unit: 'rad' },
            ],
        }
    },

    equations: {
        appLabel: 'Equations',
        LEVEL_GROUPS: {
            "Foundational Skills": [
                { key: 'oneStepEasy', name: 'One Step<br>Easy', value: 'one-step-easy' },
                { key: 'oneStepMedium', name: 'One Step<br>Medium', value: 'one-step-medium' },
                { key: 'oneStepHard', name: 'One Step<br>Hard', value: 'one-step-hard' },
                { key: 'twoStepEasy', name: 'Two Step<br>Easy', value: 'two-step-easy' },
                { key: 'twoStepMedium', name: 'Two Step<br>Medium', value: 'two-step-medium' },
                { key: 'twoStepHard', name: 'Two Step<br>Hard', value: 'two-step-hard' },
                { key: 'twoStepNegCoeffEasy', name: 'Two Step Negative Coefficients<br>Easy', value: 'two-step-neg-coeff-easy' },
                { key: 'twoStepNegCoeffMedium', name: 'Two Step Negative Coefficients<br>Medium', value: 'two-step-neg-coeff-medium' },
                { key: 'twoStepNegCoeffHard', name: 'Two Step Negative Coefficients<br>Hard', value: 'two-step-neg-coeff-hard' },
                { key: 'twoStepGroupingEasy', name: 'Two Step Grouping<br>Easy', value: 'two-step-grouping-easy' },
                { key: 'twoStepGroupingMedium', name: 'Two Step Grouping<br>Medium', value: 'two-step-grouping-medium' },
                { key: 'twoStepGroupingHard', name: 'Two Step Grouping<br>Hard', value: 'two-step-grouping-hard' },
                { key: 'mixedTwoStepEasy', name: 'Mixed Two Step<br>Easy', value: 'mixed-two-step-easy' },
                { key: 'mixedTwoStepMedium', name: 'Mixed Two Step<br>Medium', value: 'mixed-two-step-medium' },
                { key: 'mixedTwoStepHard', name: 'Mixed Two Step<br>Hard', value: 'mixed-two-step-hard' },
                { key: 'simpleQuadraticEasy', name: 'Simple Quadratic<br>Easy', value: 'simple-quadratic-easy' },
                { key: 'simpleQuadraticMedium', name: 'Simple Quadratic<br>Medium', value: 'simple-quadratic-medium' },
                { key: 'simpleQuadraticHard', name: 'Simple Quadratic<br>Hard', value: 'simple-quadratic-hard' },
                { key: 'pronumeralsBothSidesEasy', name: 'Pronumerals Both Sides<br>Easy', value: 'pronumerals-both-sides-easy' },
                { key: 'pronumeralsBothSidesMedium', name: 'Pronumerals Both Sides<br>Medium', value: 'pronumerals-both-sides-medium' },
                { key: 'pronumeralsBothSidesHard', name: 'Pronumerals Both Sides<br>Hard', value: 'pronumerals-both-sides-hard' },
            ],
            "Intermediate Skills": [
                { key: 'mixedMultistepLinearEasy',   name: 'Mixed Multistep Linear<br>Easy', value: 'mixed-multistep-linear-easy'   },
                { key: 'mixedMultistepLinearMedium', name: 'Mixed Multistep Linear<br>Medium', value: 'mixed-multistep-linear-medium' },
                { key: 'mixedMultistepLinearHard',   name: 'Mixed Multistep Linear<br>Hard', value: 'mixed-multistep-linear-hard'   },
                { key: 'nullFactorLawEasy', name: 'Null Factor Law<br>Easy', value: 'null-factor-law-easy' },
                { key: 'nullFactorLawMedium', name: 'Null Factor Law<br>Medium', value: 'null-factor-law-medium' },
                { key: 'nullFactorLawHard', name: 'Null Factor Law<br>Hard', value: 'null-factor-law-hard' },
                { key: 'monicQuadraticEasy', name: 'Monic Quadratics<br>Easy', value: 'monic-quadratic-easy' },
                { key: 'monicQuadraticMedium', name: 'Monic Quadratics<br>Medium', value: 'monic-quadratic-medium' },
                { key: 'monicQuadraticHard', name: 'Monic Quadratics<br>Hard', value: 'monic-quadratic-hard' },
                { key: 'simpleCubicEasy', name: 'Simple Cubic<br>Easy', value: 'simple-cubic-easy' },
                { key: 'simpleCubicMedium', name: 'Simple Cubic<br>Medium', value: 'simple-cubic-medium' },
                { key: 'simpleCubicHard', name: 'Simple Cubic<br>Hard', value: 'simple-cubic-hard' },
                { key: 'linearInequalitiesEasy', name: 'Linear Inequalities<br>Easy', value: 'linear-inequalities-easy' },
                { key: 'linearInequalitiesMedium', name: 'Linear Inequalities<br>Medium', value: 'linear-inequalities-medium' },
                { key: 'linearInequalitiesHard', name: 'Linear Inequalities<br>Hard', value: 'linear-inequalities-hard' },
            ],
            "Advanced Skills": [
                { key: 'algFractMonomialEasy', name: 'Algebraic Fractions - Monomial Denominator<br>Easy', value: 'alg-fract-monomial-easy' },
                { key: 'algFractMonomialMedium', name: 'Algebraic Fractions - Monomial Denominator<br>Medium', value: 'alg-fract-monomial-medium' },
                { key: 'algFractMonomialHard', name: 'Algebraic Fractions - Monomial Denominator<br>Hard', value: 'alg-fract-monomial-hard' },
                { key: 'algFractBinomialEasy', name: 'Algebraic Fractions - Binomial Denominator<br>Easy', value: 'alg-fract-binomial-easy' },
                { key: 'algFractBinomialMedium', name: 'Algebraic Fractions - Binomial Denominator<br>Medium', value: 'alg-fract-binomial-medium' },
                { key: 'algFractBinomialHard', name: 'Algebraic Fractions - Binomial Denominator<br>Hard', value: 'alg-fract-binomial-hard' },
                { key: 'algFractCrossMultiplyEasy', name: 'Algebraic Fractions - Cross Multiply<br>Easy', value: 'alg-fract-cross-multiply-easy' },
                { key: 'algFractCrossMultiplyMedium', name: 'Algebraic Fractions - Cross Multiply<br>Medium', value: 'alg-fract-cross-multiply-medium' },
                { key: 'algFractCrossMultiplyHard', name: 'Algebraic Fractions - Cross Multiply<br>Hard', value: 'alg-fract-cross-multiply-hard' },
                { key: 'algFractAlgDenomEasy', name: 'Algebraic Fractions - Algebraic Denominator<br>Easy', value: 'alg-fract-alg-denom-easy' },
                { key: 'algFractAlgDenomMedium', name: 'Algebraic Fractions - Algebraic Denominator<br>Medium', value: 'alg-fract-alg-denom-medium' },
                { key: 'algFractAlgDenomHard', name: 'Algebraic Fractions - Algebraic Denominator<br>Hard', value: 'alg-fract-alg-denom-hard' },
                { key: 'nonMonicQuadraticEasy', name: 'Non-Monic Quadratic<br>Easy', value: 'non-monic-quadratic-easy' },
                { key: 'nonMonicQuadraticMedium', name: 'Non-Monic Quadratic<br>Medium', value: 'non-monic-quadratic-medium' },
                { key: 'nonMonicQuadraticHard', name: 'Non-Monic Quadratic<br>Hard', value: 'non-monic-quadratic-hard' },
                { key: 'quadraticFormulaEasy', name: 'Quadratic Formula<br>Easy', value: 'quadratic-formula-easy' },
                { key: 'quadraticFormulaMedium', name: 'Quadratic Formula<br>Medium', value: 'quadratic-formula-medium' },
                { key: 'quadraticFormulaHard', name: 'Quadratic Formula<br>Hard', value: 'quadratic-formula-hard' },
                { key: 'substitutionEasy', name: 'Simultaneous Equations - Substitution<br>Easy', value: 'substitution-easy' },
                { key: 'substitutionMedium', name: 'Simultaneous Equations - Substitution<br>Medium', value: 'substitution-medium' },
                { key: 'substitutionHard', name: 'Simultaneous Equations - Substitution<br>Hard', value: 'substitution-hard' },
                { key: 'eliminationEasy', name: 'Simultaneous Equations - Elimination<br>Easy', value: 'elimination-easy' },
                { key: 'eliminationMedium', name: 'Simultaneous Equations - Elimination<br>Medium', value: 'elimination-medium' },
                { key: 'eliminationHard', name: 'Simultaneous Equations - Elimination<br>Hard', value: 'elimination-hard' },
                { key: 'equatingCoefficientsEasy', name: 'Equating Coefficients<br>Easy', value: 'equating-coefficients-easy' },
                { key: 'equatingCoefficientsMedium', name: 'Equating Coefficients<br>Medium', value: 'equating-coefficients-medium' },
                { key: 'equatingCoefficientsHard', name: 'Equating Coefficients<br>Hard', value: 'equating-coefficients-hard' },
                { key: 'exponentialNoLogsEasy', name: 'Exponential (No Logs)<br>Easy', value: 'exponential-no-logs-easy' },
                { key: 'exponentialNoLogsMedium', name: 'Exponential (No Logs)<br>Medium', value: 'exponential-no-logs-medium' },
                { key: 'exponentialNoLogsHard', name: 'Exponential (No Logs)<br>Hard', value: 'exponential-no-logs-hard' },
                { key: 'quadraticInequalitiesEasy', name: 'Quadratic Inequalities<br>Easy', value: 'quadratic-inequalities-easy' },
                { key: 'quadraticInequalitiesMedium', name: 'Quadratic Inequalities<br>Medium', value: 'quadratic-inequalities-medium' },
                { key: 'quadraticInequalitiesHard', name: 'Quadratic Inequalities<br>Hard', value: 'quadratic-inequalities-hard' },
                { key: 'trigEquationsEasy', name: 'Trig Equations<br>Easy', value: 'trig-equations-easy' },
                { key: 'trigEquationsMedium', name: 'Trig Equations<br>Medium', value: 'trig-equations-medium' },
                { key: 'trigEquationsHard', name: 'Trig Equations<br>Hard', value: 'trig-equations-hard' },
            ],
        }
    },
    calculus: {
        appLabel: 'Calculus',
        LEVEL_GROUPS: {
            "Differentiation": [
                { key: 'polynomialDiff',        name: 'Polynomial<br>Functions',       value: 'polynomial-diff' },
                { key: 'polynomialChainRule',    name: 'Polynomial<br>Chain Rule',      value: 'polynomial-chain-rule' },
                { key: 'polynomialProductRule',  name: 'Polynomial<br>Product Rule',    value: 'polynomial-product-rule' },
                { key: 'polynomialQuotientRule', name: 'Polynomial<br>Quotient Rule',   value: 'polynomial-quotient-rule' },
                { key: 'polynomialMixedRules',   name: 'Polynomial<br>Mixed',           value: 'polynomial-mixed-rules' },
                { key: 'exponentialDiff',        name: 'Exponential<br>Functions',      value: 'exponential-diff' },
                { key: 'exponentialDiffRules',   name: 'Exponential<br>with Rules',     value: 'exponential-diff-rules' },
                { key: 'logarithmicDiff',        name: 'Logarithmic<br>Functions',      value: 'logarithmic-diff' },
                { key: 'logarithmicDiffRules',   name: 'Logarithmic<br>with Rules',     value: 'logarithmic-diff-rules' },
                { key: 'trigDiff',               name: 'Trigonometric<br>Functions',    value: 'trig-diff' },
                { key: 'trigDiffRules',          name: 'Trigonometric<br>with Rules',   value: 'trig-diff-rules' },
                { key: 'mixedDiff',              name: 'Mixed<br>Differentiation',      value: 'mixed-diff' },
            ],
            "Integration": [
                { key: 'polynomialInt',          name: 'Polynomials',                   value: 'polynomial-int' },
                { key: 'exponentialInt',         name: 'Exponentials',                  value: 'exponential-int' },
                { key: 'rationalInt',            name: 'Rational',                      value: 'rational-int' },
                { key: 'trigInt',                name: 'Trigonometric',                 value: 'trig-int' },
                { key: 'mixedInt',               name: 'Mixed<br>Integration',          value: 'mixed-int' },
                { key: 'polynomialRCR',          name: 'Polynomial<br>Reverse Chain',   value: 'polynomial-rcr' },
                { key: 'exponentialRCR',         name: 'Exponential<br>Reverse Chain',  value: 'exponential-rcr' },
                { key: 'rationalRCR',            name: 'Rational<br>Reverse Chain',     value: 'rational-rcr' },
                { key: 'trigRCR',                name: 'Trig<br>Reverse Chain',         value: 'trig-rcr' },
                { key: 'mixedRCR',               name: 'Mixed<br>Reverse Chain',        value: 'mixed-rcr' },
            ],
            "Extension": [
                { key: 'inverseTrigDiff',             name: 'Differentiating<br>Inverse Trig',  value: 'inverse-trig-diff' },
                { key: 'inverseTrigInt',              name: 'Integrating<br>Inverse Trig',       value: 'inverse-trig-int' },
                { key: 'integrationBySubstitution',   name: 'Integration by<br>Substitution',    value: 'integration-substitution' },
                { key: 'sinCosSquaredInt',            name: 'sin² and cos²<br>Integration',      value: 'sin-cos-squared-int' },
                { key: 'extensionMixedInt',           name: 'Mixed<br>Integration',              value: 'extension-mixed-int' },
            ],
        }
    }
};
