// One-shot script: convert algebra/levels/*.js from classic-script self-registering
// globals (window.AlgebraLevels[key] = ...) to ES module default exports.
// Also generates algebra/levels/index.js barrel keyed by the registry.
//
// Run from repo root:  node scripts/convertAlgebraLevels.mjs
//
// Idempotent: skips files that already use `export default`.

import { readFile, writeFile, readdir } from 'node:fs/promises';
import { join } from 'node:path';

const LEVELS_DIR = 'algebra/levels';

// Pull canonical level keys from the registry (eval the classic script in a sandbox)
const registrySrc = await readFile('shared/levelRegistry.js', 'utf8');
const sandbox = { window: {} };
const fn = new Function('window', registrySrc);
fn(sandbox.window);
const algebraKeys = Object.values(sandbox.window.LevelRegistry.algebra.LEVEL_GROUPS)
    .flat().map(l => l.key);

let converted = 0, skipped = 0;

for (const key of algebraKeys) {
    const path = join(LEVELS_DIR, `${key}.js`);
    let src = await readFile(path, 'utf8');

    if (src.includes('export default')) {
        skipped++;
        continue;
    }

    // Normalise to LF-only so split/join doesn't strand CRs.
    src = src.replace(/\r\n/g, '\n').replace(/\r/g, '\n');

    // Strip the `window.AlgebraLevels = window.AlgebraLevels || {};` line.
    src = src.replace(/^[ \t]*window\.AlgebraLevels\s*=\s*window\.AlgebraLevels\s*\|\|\s*\{\};[ \t]*\n/gm, '');

    // Replace `window.AlgebraLevels.<key> = ` with `export default `.
    const assignRe = new RegExp(`window\\.AlgebraLevels\\.${key}[ \\t]*=[ \\t]*`, 'g');
    if (!assignRe.test(src)) {
        throw new Error(`${path}: no window.AlgebraLevels.${key} assignment found`);
    }
    src = src.replace(assignRe, 'export default ');

    // Insert BaseLevel import after the first line if it's a leading comment,
    // otherwise at the very top.
    const lines = src.split('\n');
    const insertAt = lines[0].trimStart().startsWith('//') ? 1 : 0;
    lines.splice(insertAt, 0, `import { BaseLevel } from './BaseLevel.js';`);
    src = lines.join('\n');

    await writeFile(path, src);
    converted++;
}

// Convert BaseLevel.js: add `export` keyword to class declaration.
const basePath = join(LEVELS_DIR, 'BaseLevel.js');
let baseSrc = await readFile(basePath, 'utf8');
if (!baseSrc.includes('export class BaseLevel')) {
    baseSrc = baseSrc.replace(/^\s*class\s+BaseLevel\b/m, 'export class BaseLevel');
    await writeFile(basePath, baseSrc);
    console.log('BaseLevel.js: added export keyword');
} else {
    console.log('BaseLevel.js: already exports — skipped');
}

// Generate levels/index.js barrel (re-export each level by registry key).
const barrelLines = [
    '// Auto-generated by scripts/convertAlgebraLevels.mjs',
    '// Re-exports each level keyed by its registry name so questionGenerator',
    '// can dispatch with `import * as Levels from \'./levels/index.js\'`.',
    '',
    ...algebraKeys.map(k => `export { default as ${k} } from './${k}.js';`),
    '',
];
await writeFile(join(LEVELS_DIR, 'index.js'), barrelLines.join('\n'));
console.log(`Wrote ${LEVELS_DIR}/index.js with ${algebraKeys.length} re-exports`);

console.log(`\nDone. Converted: ${converted}, already-converted: ${skipped}, total keys: ${algebraKeys.length}`);
